In [1]:
import pandas as pd

In [2]:
# read base zoning input files

z_p = pd.read_csv(r'C:\Users\ywang\Box\Modeling and Surveys\Urban Modeling\Bay Area UrbanSim\PBA50\Current PBA50 Large General Input Data\2020_11_05_zoning_parcels_hybrid_pba50.csv',
                  usecols = ['PARCEL_ID', 'geom_id', 'zoning_id'])
z_lookup = pd.read_csv(r'C:\Users\ywang\Box\Modeling and Surveys\Urban Modeling\Bay Area UrbanSim\PBA50\Current PBA50 Large General Input Data\2020_11_05_zoning_lookup_hybrid_pba50.csv')
basezoning = z_p.merge(z_lookup, left_on = 'zoning_id', right_on = 'id', how='left')
print('basezoning has {} records'.format(basezoning.shape[0]))

basezoning has 1950732 records

In [3]:
# rename columns
basezoning.rename(columns = {'juris': 'juris_basezoning',
                             'max_dua': 'max_dua_basezoning',
                             'max_far': 'max_far_basezoning',
                             'HS': 'HS_basezoning',
                             'HT': 'HT_basezoning', 
                             'HM': 'HM_basezoning',
                             'OF': 'OF_basezoning',
                             'HO': 'HO_basezoning',
                             'SC': 'SC_basezoning',
                             'IL': 'IL_basezoning',
                             'IW': 'IW_basezoning',
                             'IH': 'IH_basezoning',
                             'RS': 'RS_basezoning',
                             'RB': 'RB_basezoning',
                             'MR': 'MR_basezoning',
                             'MT': 'MR_basezoning',
                             'ME': 'ME_basezoning'}, inplace=True)
display(basezoning.head())

,PARCEL_ID,geom_id,zoning_id,id,juris_basezoning,name,max_dua_basezoning,max_far_basezoning,max_height,HS_basezoning,...,HO_basezoning,SC_basezoning,IL_basezoning,IW_basezoning,IH_basezoning,RS_basezoning,RB_basezoning,MR_basezoning,MR_basezoning,ME_basezoning
0,229116,10305106092872,461,461,livermore,NODEV_pba40,NaN,NaN,NaN,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,244166,11107351665227,462,462,livermore,GP-UM_pba40,14.00,NaN,35.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,202378,11030175960628,401,401,hayward,LDR_pba40,8.70,2.000000,30.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2004420,6381677629073,8282,8282,unincorporated_sonoma,LEA60_pba40,0.67,2.333333,35.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,340332,314875459798,286,286,fremont,RESM4_pba40,23.00,3.466667,30.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
# read zoningmods input files

p_g = pd.read_csv(r'C:\Users\ywang\Box\Modeling and Surveys\Urban Modeling\Bay Area UrbanSim\PBA50\PBA50 Final Blueprint Large General Input Data\2020_11_10_parcels_geography.csv',
                  usecols = ['PARCEL_ID', 'fbpzoningmodcat', 'nodev'])
zmods = pd.read_csv(r'C:\Users\ywang\Documents\GitHub\bayarea_urbansim\data\zoning_mods_24.csv')
zoningmods = p_g.merge(zmods, on='fbpzoningmodcat', how='left')
print('zoningmods has {} records'.format(zoningmods.shape[0]))

zoningmods has 1956208 records

In [5]:
zoningmods.head()

,PARCEL_ID,fbpzoningmodcat,nodev,modcat_id,FREQUENCY,SUM_ACRES,manual_county,zone,juris,gg_id,...,add_bldg,drop_bldg,dua_up,far_up,dua_down,far_down,subsidy,notes,res_rent_cat,job_out_cat
0,229116,livermoreNANAHRADISNAinNA,0.0,782,462,501.766781,1,725,livermore,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,244166,livermoreNAtra3DISNAinNA,0.0,793,3041,1998.371566,1,715,livermore,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,202378,haywardNANANANAinNA,0.0,684,1446,1388.870289,1,820,hayward,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2004420,unincorporated_sonomaNANAHRADISNAoutNA,0.0,2768,2947,140734.550800,97,1401,unincorporated_sonoma,NaN,...,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN
4,340332,fremontNANAHRADISNAinNA,1.0,603,6692,2717.938841,1,763,fremont,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
zoningmerge = basezoning.merge(zoningmods, on='PARCEL_ID', how='outer')
print('zoningmerge has {} records'.format(zoningmerge.shape[0]))

# create temporary fields to fill na in max_dua_basezoning and dua_up 
zoningmerge['dua_up_temp'] = zoningmerge['dua_up'].fillna(0)
zoningmerge['max_dua_basezoning_temp'] = zoningmerge['max_dua_basezoning'].fillna(0)
display(zoningmerge[['PARCEL_ID', 'juris', 'max_dua_basezoning','dua_up']])

zoningmerge has 1956208 records

         PARCEL_ID                  juris  max_dua_basezoning  dua_up
0           229116              livermore                 NaN     NaN
1           244166              livermore               14.00     NaN
2           202378                hayward                8.70     NaN
3          2004420  unincorporated_sonoma                0.67     NaN
4           340332                fremont               23.00     NaN
...            ...                    ...                 ...     ...
1956203     650584              pittsburg                 NaN    35.0
1956204     650683              pittsburg                 NaN    35.0
1956205     651123              pittsburg                 NaN    35.0
1956206     680555                 moraga                 NaN     NaN
1956207    1417213               campbell                 NaN    35.0

[1956208 rows x 4 columns]

In [7]:
# calculate final max_dua used in urbansim
zoningmerge['max_dua_urbansim'] = zoningmerge['max_dua_basezoning_temp']
zoningmerge['max_dua_source'] = 'basezoning'
zoningmerge.loc[zoningmerge.dua_up_temp > zoningmerge.max_dua_basezoning_temp,
                'max_dua_source'] = 'zoningmods'
zoningmerge.loc[zoningmerge.dua_up_temp > zoningmerge.max_dua_basezoning_temp,
                'max_dua_urbansim'] = zoningmerge['dua_up_temp']

In [8]:
# export with key needed fields
zoningmerge_dua = zoningmerge[['PARCEL_ID', 'juris', 'max_dua_urbansim', 'max_dua_source', 'max_dua_basezoning', 'dua_up']]
display(zoningmerge_dua)

zoningmerge_dua.to_csv(r'M:\Data\Urban\BAUS\PBA50\Final_Blueprint\Zoning Modifications\final_zoning_urbansim\zoning_urbansim_max_dua.csv', index=False)

,PARCEL_ID,juris,max_dua_urbansim,max_dua_source,max_dua_basezoning,dua_up
0,229116,livermore,0.00,basezoning,NaN,NaN
1,244166,livermore,14.00,basezoning,14.00,NaN
2,202378,hayward,8.70,basezoning,8.70,NaN
3,2004420,unincorporated_sonoma,0.67,basezoning,0.67,NaN
4,340332,fremont,23.00,basezoning,23.00,NaN
...,...,...,...,...,...,...
1956203,650584,pittsburg,35.00,zoningmods,NaN,35.0
1956204,650683,pittsburg,35.00,zoningmods,NaN,35.0
1956205,651123,pittsburg,35.00,zoningmods,NaN,35.0
1956206,680555,moraga,0.00,basezoning,NaN,NaN
1956207,1417213,campbell,35.00,zoningmods,NaN,35.0

In [10]:
# export San Francisco data

zoningmerge_dua_sanfrancisco = zoningmerge_dua.loc[zoningmerge_dua.juris == 'san_francisco']
print('export {} records for San Francisco'.format(zoningmerge_dua_sanfrancisco.shape[0]))
zoningmerge_dua_sanfrancisco.to_csv(r'M:\Data\Urban\BAUS\PBA50\Final_Blueprint\Zoning Modifications\final_zoning_urbansim\zoning_urbansim_max_dua_sanfrancisco.csv', index=False)

export 153355 records for San Francisco