## Jobs-Housing Fit
The purpose of this book is to calculate the jobs-housing fit by jurisdiction/superdistrict
work on personal laptop jupyter

In [55]:
import numpy as np
import pandas as pd

Adding and Cleaning Jurisdictions

In [95]:
#new path
juris_15=pd.read_csv('/Users/jeremyhalpern/Desktop/JHFit/run98_juris_summaries_2015.csv')
juris_50=pd.read_csv('/Users/jeremyhalpern/Desktop/JHFit/run98_juris_summaries_2050.csv')
sd_15=pd.read_csv('/Users/jeremyhalpern/Desktop/JHFit/run98_superdistrict_summaries_2015.csv')
sd_50=pd.read_csv('/Users/jeremyhalpern/Desktop/JHFit/run98_superdistrict_summaries_2050.csv')
juris2county=pd.read_csv('/Users/jeremyhalpern/Desktop/JHFit/Juris_to_County.csv')
sd2county=pd.read_csv('/Users/jeremyhalpern/Desktop/JHFit/Superdistrict_County.csv')
sdnames=pd.read_csv('/Users/jeremyhalpern/Desktop/JHFit/SD_names.csv')

In [96]:
#Fix run98 industry types
juris_15.rename(columns = {'agrempn':'AGREMPN', 'mwtempn':'FPSEMPN','retempn':'HEREMPN', 
                        'fpsempn':'MWTEMPN', 'herempn':'OTHEMPN','othempn':'RETEMPN'}, inplace = True)
juris_50.rename(columns = {'agrempn':'AGREMPN', 'mwtempn':'FPSEMPN','retempn':'HEREMPN', 
                        'fpsempn':'MWTEMPN', 'herempn':'OTHEMPN','othempn':'RETEMPN'}, inplace = True)
sd_15.rename(columns = {'agrempn':'AGREMPN', 'mwtempn':'FPSEMPN','retempn':'HEREMPN', 
                        'fpsempn':'MWTEMPN', 'herempn':'OTHEMPN','othempn':'RETEMPN'}, inplace = True)
sd_50.rename(columns = {'agrempn':'AGREMPN', 'mwtempn':'FPSEMPN','retempn':'HEREMPN', 
                        'fpsempn':'MWTEMPN', 'herempn':'OTHEMPN','othempn':'RETEMPN'}, inplace = True)

In [97]:
sd2county

    FID  county_fip  suprdistid  SHAPE_Length  SHAPE_Area
0     1        6075           1      0.409882    0.001322
1     2        6075           2      0.313229    0.003223
2     3        6075           3      0.687548    0.005276
3     4        6075           4      0.230088    0.002668
4     5        6081           5      1.010392    0.015263
5     6        6081           6      1.505824    0.033745
6     7        6081           7      2.081636    0.070958
7     8        6085           8      0.926418    0.022105
8     9        6085           9      0.887181    0.019715
9    10        6085          10      1.125315    0.032925
10   11        6085          11      0.525039    0.009241
11   12        6085          12      0.775581    0.022156
12   13        6085          13      0.734941    0.015421
13   14        6085          14      3.143159    0.219716
14   15        6001          15      1.772165    0.110874
15   16        6001          16      1.153222    0.029373
16   17        6001          17      1.644520    0.034673
17   18        6001          18      1.463774    0.016978
18   19        6001          19      0.517362    0.004844
19   20        6013          20      1.226243    0.029599
20   21        6013          21      1.446638    0.031289
21   22        6013          22      0.969446    0.020972
22   23        6013          23      1.304988    0.047555
23   24        6013          24      1.900033    0.069434
24   25        6095          25      1.159460    0.020154
25   26        6095          26      3.035545    0.206673
26   27        6055          27      1.307407    0.034275
27   28        6055          28      2.233162    0.176670
28   29        6097          29      1.795624    0.087622
29   30        6097          30      1.742286    0.069604
30   31        6097          31      3.187939    0.268286
31   32        6041          32      0.818591    0.015460
32   33        6041          33      3.638748    0.105951
33   34        6041          34      1.581607    0.018193

In [98]:
#Add jurisdictions
#county_15=pd.read_csv(r"C:\Users\jhalpern\Box\Modeling and Surveys\Urban Modeling\Bay Area UrbanSim 1.5\PBA50\Draft Blueprint runs\Blueprint Plus Crossing (s23)\v1.7.1- FINAL DRAFT BLUEPRINT\run98_county_summaries_2015.csv")
#county_50=pd.read_csv(r"C:\Users\jhalpern\Box\Modeling and Surveys\Urban Modeling\Bay Area UrbanSim 1.5\PBA50\Draft Blueprint runs\Blueprint Plus Crossing (s23)\v1.7.1- FINAL DRAFT BLUEPRINT\run98_county_summaries_2050.csv")
#juris_15=pd.read_csv(r"C:\Users\jhalpern\Box\Modeling and Surveys\Urban Modeling\Bay Area UrbanSim 1.5\PBA50\Draft Blueprint runs\Blueprint Plus Crossing (s23)\v1.7.1- FINAL DRAFT BLUEPRINT\run98_juris_summaries_2015.csv")
#juris_50=pd.read_csv(r"C:\Users\jhalpern\Box\Modeling and Surveys\Urban Modeling\Bay Area UrbanSim 1.5\PBA50\Draft Blueprint runs\Blueprint Plus Crossing (s23)\v1.7.1- FINAL DRAFT BLUEPRINT\run98_juris_summaries_2050.csv")
#juris2county=pd.read_csv(r"C:\Users\jhalpern\Desktop\Jobs-Housing Balance\Juris_to_County.csv")

In [99]:
print(juris_15)

               juris  tothh  hhincq1  hhincq2  hhincq3  hhincq4     sfdu  \
0            Alameda  30148     8948     7763     6042     7395  15321.0
1     Alameda County  49403    13210    12619    10898    12676  38359.0
2             Albany   7435     2259     1920     1468     1788   4166.0
3    American Canyon   5540     1514     1544     1367     1115   4244.0
4            Antioch  32856     7747     8705     8396     8008  28874.0
..               ...    ...      ...      ...      ...      ...      ...
104          Vallejo  41571    11797    11066     9614     9094  28920.0
105     Walnut Creek  31050     7453     7417     6742     9438  17045.0
106          Windsor   9017     2048     2342     2332     2295   8349.0
107         Woodside   2217      149      241      459     1368   2225.0
108       Yountville   1141      323      339      226      253    864.0

        mfdu  totemp  AGREMPN  ...  occupancy_rate  non_residential_sqft  \
0    15368.0   31856     19.0  ...        0.982372          1.994980e+07
1    12793.0   23613     90.0  ...        0.965808          2.036406e+07
2     3130.0    4453      2.0  ...        1.019052          2.495248e+06
3     1745.0    6250    127.0  ...        0.925029          6.246233e+06
4     6188.0   21888     50.0  ...        0.937083          1.619706e+07
..       ...     ...      ...  ...             ...                   ...
104  13182.0   28048    115.0  ...        0.987388          1.667860e+07
105  15783.0   50440     57.0  ...        0.945839          2.491662e+07
106   1417.0    7226    358.0  ...        0.923305          5.538146e+06
107      2.0    1788     71.0  ...        0.995510          9.652720e+05
108    393.0    2167    145.0  ...        0.907717          1.687498e+06

     sq_ft_per_employee  deed_restricted_units  inclusionary_units  \
0            626.249466                    NaN                 NaN
1            862.409008                   33.0                33.0
2            560.352122                    NaN                 NaN
3            999.397280                    NaN                 NaN
4            739.997442                    NaN                 NaN
..                  ...                    ...                 ...
104          594.644859                    NaN                 NaN
105          493.985428                    NaN                 NaN
106          766.419319                    NaN                 NaN
107          539.861298                    8.0                 8.0
108          778.725427                    NaN                 NaN

     subsidized_units  inclusionary_revenue_reduction  \
0                 NaN                             NaN
1                 0.0                    2.248192e+07
2                 NaN                             NaN
3                 NaN                             NaN
4                 NaN                             NaN
..                ...                             ...
104               NaN                             NaN
105               NaN                             NaN
106               NaN                             NaN
107               0.0                    1.198094e+07
108               NaN                             NaN

     inclusionary_revenue_reduction_per_unit  total_subsidy  subsidy_per_unit
0                                        NaN            NaN               NaN
1                               6.812702e+05            NaN               NaN
2                                        NaN            NaN               NaN
3                                        NaN            NaN               NaN
4                                        NaN            NaN               NaN
..                                       ...            ...               ...
104                                      NaN            NaN               NaN
105                                      NaN            NaN               NaN
106                                      NaN            NaN               NaN
107                             1.497618e+06            NaN               NaN
108                                      NaN            NaN               NaN

[109 rows x 25 columns]

In [100]:
#Add county names to juris2county
lst = {'County':['Alameda','Contra Costa','Marin','Napa','San Francisco',
                  'San Mateo','Santa Clara','Solano','Sonoma'], 
        'fips_county':[1,13,41,55,75,81,85,95,97]} 
cty = pd.DataFrame(lst) 
print(cty)

          County  fips_county
0        Alameda            1
1   Contra Costa           13
2          Marin           41
3           Napa           55
4  San Francisco           75
5      San Mateo           81
6    Santa Clara           85
7         Solano           95
8         Sonoma           97

In [101]:
sd2county.head()

   FID  county_fip  suprdistid  SHAPE_Length  SHAPE_Area
0    1        6075           1      0.409882    0.001322
1    2        6075           2      0.313229    0.003223
2    3        6075           3      0.687548    0.005276
3    4        6075           4      0.230088    0.002668
4    5        6081           5      1.010392    0.015263

In [102]:
#Add county names
sd2county['fip_co']=sd2county['county_fip']-6000
juris2cty=pd.merge(juris2county,cty,left_on='fipco', right_on='fips_county',how='left')
juris2cty.drop(['Shape__Area','Shape__Length','fips_county','fipst','objectid'], inplace=True,axis=1)
sd2cty=pd.merge(sd2county,cty,left_on='fip_co', right_on='fips_county',how='left')
sd2cty=pd.merge(sd2cty,sdnames,left_on='suprdistid', right_on='SD_ID',how='left')
sd2cty.drop(['SHAPE_Area','SHAPE_Length','county_fip','FID','fips_county','suprdistid'], inplace=True,axis=1)

In [103]:
sd2cty

    fip_co         County  SD_ID                         SD_NAME
0       75  San Francisco      1  Greater Downtown San Francisco
1       75  San Francisco      2               Richmond District
2       75  San Francisco      3                Mission District
3       75  San Francisco      4                 Sunset District
4       81      San Mateo      5             Daly City/San Bruno
5       81      San Mateo      6            San Mateo/Burlingame
6       81      San Mateo      7         Redwood City/Menlo Park
7       85    Santa Clara      8             Palo Alto/Los Altos
8       85    Santa Clara      9         Sunnyvale/Mountain View
9       85    Santa Clara     10              Cupertino/Saratoga
10      85    Santa Clara     11                Central San Jose
11      85    Santa Clara     12          Milpitas/East San Jose
12      85    Santa Clara     13                  South San Jose
13      85    Santa Clara     14              Gilroy/Morgan Hill
14       1        Alameda     15            Livermore/Pleasanton
15       1        Alameda     16              Fremont/Union City
16       1        Alameda     17             Hayward/San Leandro
17       1        Alameda     18                 Oakland/Alameda
18       1        Alameda     19                 Berkeley/Albany
19      13   Contra Costa     20             Richmond/El Cerrito
20      13   Contra Costa     21                Concord/Martinez
21      13   Contra Costa     22                    Walnut Creek
22      13   Contra Costa     23              Danville/San Ramon
23      13   Contra Costa     24               Antioch/Pittsburg
24      95         Solano     25                 Vallejo/Benicia
25      95         Solano     26             Fairfield/Vacaville
26      55           Napa     27                            Napa
27      55           Napa     28                    Saint Helena
28      97         Sonoma     29           Petaluma/Rohnert Park
29      97         Sonoma     30           Santa Rosa/Sebastopol
30      97         Sonoma     31           Healdsburg/Cloverdale
31      41          Marin     32                          Novato
32      41          Marin     33                      San Rafael
33      41          Marin     34           Mill Valley/Sausalito

In [104]:
#Add unincorpated County juris
#didn't do in the end just using county summaries
lst2 = {'County':['Alameda','Contra Costa','Marin','Napa',
                  'San Mateo','Santa Clara','Solano','Sonoma'], 
        'jurname':['Alameda County','Contra Costa County','Marin County','Napa County',
                  'San Mateo County','Santa Clara County','Solano County','Sonoma County']}
unincorp = pd.DataFrame(lst2) 
mapjuris2cty=juris2cty.append(unincorp, sort=False)

In [105]:
#Merge with juris_15 and juris_50
juris2015=pd.merge(juris_15,mapjuris2cty,left_on='juris', right_on='jurname',how='left')
juris2050=pd.merge(juris_50,mapjuris2cty,left_on='juris', right_on='jurname',how='left')

In [106]:
#Repeat with Superdistricts
SD2015=pd.merge(sd_15,sd2cty,left_on='superdistrict', right_on='SD_ID',how='left')
SD2050=pd.merge(sd_50,sd2cty,left_on='superdistrict', right_on='SD_ID',how='left')

In [107]:
SD2015[['SD_ID','AGREMPN','HEREMPN','FPSEMPN','MWTEMPN','OTHEMPN','RETEMPN']]

    SD_ID  AGREMPN  HEREMPN  FPSEMPN  MWTEMPN  OTHEMPN  RETEMPN
0       1      426   164532    68707   112613   120910    36797
1       2      113    30164     6738     9144    31076    11896
2       3      288   100846    75069    26718    78450    18619
3       4       23    12472     2216     3507    10379     3279
4       5      455    30043    41316    14756    24219     7949
5       6      658    25983    17027    24066    20451     6837
6       7     1332    27516    40999    24998    27068    13575
7       8      200    38321    33361    26540    54093     8380
8       9      737    50443   202908    50776    38724    23664
9      10      299    47719    28095    18079    28291    10932
10     11      386    55351    37568    23800    28558    20078
11     12      302    28786    37365    12856    17776    12175
12     13      305    17520    11224     8323     9734     4109
13     14     2684    15265    14038     5072     6858     3880
14     15      581    41171    27186    23592    16711    14568
15     16      213    34659    56990    17218    19542     9121
16     17      149    40127    57875    12774    23459    13867
17     18      344    84561    57874    27067    61315    32623
18     19       76    43724    20243    23168    43985    10707
19     20      234    27885    20377     7140    13578     6437
20     21      220    39940    20347    14988    22060    12791
21     22      101    25449     8330    16230    19059     4981
22     23      527    16493     9147    12606    11693    10427
23     24      359    23700     6545     6328    10463     5142
24     25      138    14246     9441     4303     8545     5435
25     26     1754    29050    17948     6098    16491    10947
26     27      804    14206    11387     4428     8804     4293
27     28     3781     2735     5814     1552     3345     2221
28     29     2129    20996    14841     8552    12782     6198
29     30     1808    37532    21141    12271    22800    11093
30     31     2769     7130     6211     2425     5044     3306
31     32      111     7514     3977     6734     5258     2332
32     33      414    19438     7797     8453    13081     6371
33     34      174    13918     3515     6414    11111     3040

In [134]:
#Confirm no missing values for County
filtered_df = juris2015[juris2015['County'].isnull()]
print(filtered_df)

Empty DataFrame
Columns: [juris, tothh, hhincq1, hhincq2, hhincq3, hhincq4, sfdu, mfdu, totemp, agrempn, mwtempn, retempn, fpsempn, herempn, othempn, occupancy_rate, non_residential_sqft, sq_ft_per_employee, deed_restricted_units, inclusionary_units, subsidized_units, inclusionary_revenue_reduction, inclusionary_revenue_reduction_per_unit, total_subsidy, subsidy_per_unit, fipco, jurname, County]
Index: []

In [315]:
juris2015

               juris  tothh  hhincq1  ...  fipco          jurname        County
0            Alameda  30148     8948  ...    1.0          Alameda       Alameda
1     Alameda County  49403    13210  ...    NaN   Alameda County       Alameda
2             Albany   7435     2259  ...    1.0           Albany       Alameda
3    American Canyon   5540     1514  ...   55.0  American Canyon          Napa
4            Antioch  32856     7747  ...   13.0          Antioch  Contra Costa
..               ...    ...      ...  ...    ...              ...           ...
104          Vallejo  41571    11797  ...   95.0          Vallejo        Solano
105     Walnut Creek  31050     7453  ...   13.0     Walnut Creek  Contra Costa
106          Windsor   9017     2048  ...   97.0          Windsor        Sonoma
107         Woodside   2217      149  ...   81.0         Woodside     San Mateo
108       Yountville   1141      323  ...   55.0       Yountville          Napa

[109 rows x 28 columns]

Next part is test if wanting to pivot instead on Industry
Note: unfinished

In [321]:
j2015_pivot=pd.wide_to_long(juris2015, stubnames='Industry', i=['juris', 'tothh','hhincq1'], j=["agrempn"])

AttributeError: 'DataFrame' object has no attribute 'str'

Calculate Low-wage shares by County and MTC industry type

In [201]:
#Load employment-based and residence-based jobs data
jobs_EB=pd.read_csv(r"C:\Users\jhalpern\Documents\R\PBA2050\Outputs\Jobs-HousingFit\PUMS2014-2018 Income by Industry and Emp County.csv")
jobs_RB=pd.read_csv(r"C:\Users\jhalpern\Documents\R\PBA2050\Outputs\Jobs-HousingFit\PUMS2014-2018 Income by Industry and Res County.csv")

FileNotFoundError: [Errno 2] File b'C:\\Users\\jhalpern\\Documents\\R\\PBA2050\\Outputs\\Jobs-HousingFit\\PUMS2014-2018 Income by Industry and Emp County.csv' does not exist: b'C:\\Users\\jhalpern\\Documents\\R\\PBA2050\\Outputs\\Jobs-HousingFit\\PUMS2014-2018 Income by Industry and Emp County.csv'

In [102]:
#Note uncoded are not included
jobs_EB['tot_pwgt'] = jobs_EB['1_less than 40k']+jobs_EB['2_40k to 49,999']+jobs_EB['3_50k to 79,999']+jobs_EB['4_80k to 99,999']+jobs_EB['5_100k to 149,999']+jobs_EB['6_150k to 249,999']+jobs_EB['7_250k+']

In [103]:
jobs_EB['shareLW_Under40k']=jobs_EB['1_less than 40k']/jobs_EB['tot_pwgt']
jobs_EB['shareLW_Under50k']=(jobs_EB['1_less than 40k']+jobs_EB['2_40k to 49,999'])/jobs_EB['tot_pwgt']
jobs_EB['shareLW_Under80k']=(jobs_EB['1_less than 40k']+jobs_EB['2_40k to 49,999']+jobs_EB['3_50k to 79,999'])/jobs_EB['tot_pwgt']

In [104]:
#There is a significant difference between using less than $40k and less than $50k
#Measure and describe the difference
jobs_EB['diff40kto50k']=jobs_EB['2_40k to 49,999']/jobs_EB['tot_pwgt']
jobs_EB[["shareLW_Under40k","shareLW_Under50k","diff40kto50k"]].describe()

       shareLW_Under40k  shareLW_Under50k  diff40kto50k
count         63.000000         63.000000     63.000000
mean           0.107373          0.159244      0.051871
std            0.048279          0.063976      0.026254
min            0.000000          0.053191      0.017473
25%            0.074745          0.120876      0.037670
50%            0.101639          0.156104      0.050984
75%            0.133947          0.187091      0.057982
max            0.244444          0.407677      0.171799

In [351]:
#Number of NaN (Industry) is 22,633
jobs_EB[jobs_EB['Industry'].isnull()]['tot_pwgt'].sum()

22633

Group by County

In [109]:
jobs_county=jobs_EB.groupby("County_Emp").sum()

In [110]:
#Total person weights similar to Vital Signs employment numbers
jobs_county['tot_pwgt'].sum()

3917387

In [111]:
#Recalculate shares using county numbers (for later comparison)
jobs_county['shareLW_Under40k']=jobs_county['1_less than 40k']/jobs_county['tot_pwgt']
jobs_county['shareLW_Under50k']=(jobs_county['1_less than 40k']+jobs_county['2_40k to 49,999'])/jobs_county['tot_pwgt']
jobs_county['shareLW_Under80k']=(jobs_county['1_less than 40k']+jobs_county['2_40k to 49,999']+jobs_county['3_50k to 79,999'])/jobs_county['tot_pwgt']
jobs_county['diff40kto50k']=jobs_county['2_40k to 49,999']/jobs_county['tot_pwgt']
jobs_county[["shareLW_Under40k","shareLW_Under50k","diff40kto50k"]].describe()

       shareLW_Under40k  shareLW_Under50k  diff40kto50k
count          9.000000          9.000000      9.000000
mean           0.095697          0.140982      0.045284
std            0.020466          0.032012      0.012173
min            0.066721          0.099290      0.031859
25%            0.081382          0.113241      0.032568
50%            0.099691          0.144602      0.045766
75%            0.114131          0.162430      0.048300
max            0.123165          0.186277      0.063772

In [112]:
jobs_county

               1_less than 40k  2_40k to 49,999  ...  shareLW_Under80k  diff40kto50k
County_Emp                                       ...
Alameda                  74461            32719  ...          0.296983      0.044143
Contra Costa             36460            17991  ...          0.293086      0.045766
Marin                    12478             5746  ...          0.297746      0.045907
Napa                      8758             4846  ...          0.370259      0.063772
San Francisco            59125            23146  ...          0.231525      0.031859
San Mateo                26778            13071  ...          0.217192      0.032568
Santa Clara              72764            34525  ...          0.210512      0.032134
Solano                   18399             9428  ...          0.376457      0.063112
Sonoma                   26281            11122  ...          0.364232      0.048300

[9 rows x 13 columns]

Group by Industry

In [113]:
jobs_industry=jobs_EB.groupby("Industry").sum()

In [114]:
jobs_industry

          1_less than 40k  2_40k to 49,999  ...  shareLW_Under80k  diff40kto50k
Industry                                    ...
AGREMPN              5286             2382  ...          4.047550      0.689407
FPSEMPN             59076            26497  ...          2.149719      0.328751
HEREMPN            150848            63616  ...          2.998408      0.454093
MWTEMPN             37201            19536  ...          2.301390      0.337755
OTHEMPN             38014            22326  ...          2.484367      0.429357
RETEMPN             42445            16911  ...          3.181072      0.455835

[6 rows x 13 columns]

In [115]:
#Recalculate shares using grouped numbers (for later comparison)
jobs_industry['shareLW_Under40k']=jobs_industry['1_less than 40k']/jobs_industry['tot_pwgt']
jobs_industry['shareLW_Under50k']=(jobs_industry['1_less than 40k']+jobs_industry['2_40k to 49,999'])/jobs_industry['tot_pwgt']
jobs_industry['shareLW_Under80k']=(jobs_industry['1_less than 40k']+jobs_industry['2_40k to 49,999']+jobs_industry['3_50k to 79,999'])/jobs_industry['tot_pwgt']
jobs_industry['diff40kto50k']=jobs_industry['2_40k to 49,999']/jobs_industry['tot_pwgt']
jobs_industry[["shareLW_Under40k","shareLW_Under50k","diff40kto50k"]].describe()

       shareLW_Under40k  shareLW_Under50k  diff40kto50k
count          6.000000          6.000000      6.000000
mean           0.098501          0.143566      0.045065
std            0.044883          0.062502      0.018086
min            0.056276          0.085829      0.027055
25%            0.062650          0.093166      0.032390
50%            0.091905          0.136429      0.044176
75%            0.117867          0.165493      0.047974
max            0.171501          0.248783      0.077282

In [117]:
jobs_industry

          1_less than 40k  2_40k to 49,999  ...  shareLW_Under80k  diff40kto50k
Industry                                    ...
AGREMPN              5286             2382  ...          0.477516      0.077282
FPSEMPN             59076            26497  ...          0.187269      0.027055
HEREMPN            150848            63616  ...          0.318446      0.048148
MWTEMPN             37201            19536  ...          0.219564      0.029553
OTHEMPN             38014            22326  ...          0.242974      0.040900
RETEMPN             42445            16911  ...          0.331145      0.047452

[6 rows x 13 columns]

In [116]:
#Compare distribution of Agriculture to regional values
jobs_EB.loc[jobs_EB['Industry'] == 'AGREMPN'][["shareLW_Under40k","shareLW_Under50k","diff40kto50k"]].describe()

       shareLW_Under40k  shareLW_Under50k  diff40kto50k
count          9.000000          9.000000      9.000000
mean           0.174967          0.251568      0.076601
std            0.045190          0.072058      0.035657
min            0.125806          0.181818      0.046214
25%            0.135072          0.215313      0.053559
50%            0.161754          0.228842      0.065673
75%            0.213759          0.296693      0.082609
max            0.244444          0.407677      0.163232

## Repeat with Earnings for Comparison

In [108]:
#Load employment-based and residence-based earnings data
earn_EB=pd.read_csv("/Users/jeremyhalpern/Desktop/JHFit/PUMS2014-2018 Earnings by Industry and Emp County.csv")

In [109]:
earn_EB.head()

,County_Emp,Industry,1_less than 30k,"2_30k to 39,999","3_40k to 49,999","4_50k to 79,999","5_80k to 99,999","6_100k to 149,999","7_150k to 249,999",8_250k+
0,Alameda,AGREMPN,1479,138,329,445,174,186,72,27
1,Alameda,FPSEMPN,44268,11611,11162,26941,15270,24819,14657,4468
2,Alameda,HEREMPN,120340,28599,23699,48282,17829,21175,9677,3598
3,Alameda,MWTEMPN,35805,16236,14354,34656,12477,19812,9998,3570
4,Alameda,NaN,2289,512,441,820,208,432,246,33

In [110]:
earn_EB['tot_pwgt'] = earn_EB['1_less than 30k']+earn_EB['2_30k to 39,999']+earn_EB['3_40k to 49,999']+earn_EB['4_50k to 79,999']+earn_EB['5_80k to 99,999']+earn_EB['6_100k to 149,999']+earn_EB['7_150k to 249,999']+earn_EB['8_250k+']

In [111]:
earn_EB['shareLW_Under30k']=earn_EB['1_less than 30k']/earn_EB['tot_pwgt']
earn_EB['shareLW_Under40k']=(earn_EB['1_less than 30k']+earn_EB['2_30k to 39,999'])/earn_EB['tot_pwgt']
earn_EB['shareLW_Under50k']=(earn_EB['1_less than 30k']+earn_EB['2_30k to 39,999']+earn_EB['3_40k to 49,999'])/earn_EB['tot_pwgt']

In [112]:
earn_EB

,County_Emp,Industry,1_less than 30k,"2_30k to 39,999","3_40k to 49,999","4_50k to 79,999","5_80k to 99,999","6_100k to 149,999","7_150k to 249,999",8_250k+,tot_pwgt,shareLW_Under30k,shareLW_Under40k,shareLW_Under50k
0,Alameda,AGREMPN,1479,138,329,445,174,186,72,27,2850,0.518947,0.567368,0.682807
1,Alameda,FPSEMPN,44268,11611,11162,26941,15270,24819,14657,4468,153196,0.288963,0.364755,0.437616
2,Alameda,HEREMPN,120340,28599,23699,48282,17829,21175,9677,3598,273199,0.440485,0.545167,0.631913
3,Alameda,MWTEMPN,35805,16236,14354,34656,12477,19812,9998,3570,146908,0.243724,0.354242,0.451950
4,Alameda,NaN,2289,512,441,820,208,432,246,33,4981,0.459546,0.562337,0.650873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Sonoma,HEREMPN,46608,9740,7234,14182,4336,4339,1468,835,88742,0.525208,0.634964,0.716481
59,Sonoma,MWTEMPN,11235,4026,4340,9298,2614,3479,1784,787,37563,0.299098,0.406277,0.521817
60,Sonoma,NaN,693,68,57,238,14,20,40,13,1143,0.606299,0.665792,0.715661
61,Sonoma,OTHEMPN,9796,3274,3083,6844,2814,3046,1100,279,30236,0.323985,0.432266,0.534231
62,Sonoma,RETEMPN,16807,3957,2388,3014,658,601,439,112,27976,0.600765,0.742208,0.827566

## Combine shares and juris/county summary

In [200]:
#Before merging, need to pivot Industry from rows to columns
jobs_EB.rename(inplace=True,columns={"shareLW_Under40k": "Under40k", "shareLW_Under50k": "Under50k","shareLW_Under80k": "Under80k"})
jobs_pivot=jobs_EB.pivot(index='County_Emp', columns='Industry', values=['Under40k','Under50k','Under80k'])

NameError: name 'jobs_EB' is not defined

In [298]:
jobs_pivot

               Under40k                      ...  Under80k
Industry            NaN   AGREMPN   FPSEMPN  ...   MWTEMPN   OTHEMPN   RETEMPN
County_Emp                                   ...
Alameda        0.144467  0.161754  0.076091  ...  0.277227  0.282801  0.348883
Contra Costa   0.137080  0.135072  0.073399  ...  0.238107  0.288415  0.345878
Marin          0.063209  0.125806  0.085293  ...  0.203981  0.291481  0.374490
Napa           0.000000  0.213759  0.101639  ...  0.334111  0.321133  0.408079
San Francisco  0.122653  0.182628  0.046273  ...  0.239142  0.206635  0.281152
San Mateo      0.083723  0.231020  0.047338  ...  0.191129  0.178340  0.281970
Santa Clara    0.085836  0.130315  0.047405  ...  0.146322  0.198401  0.303350
Solano         0.147287  0.244444  0.132822  ...  0.358011  0.373042  0.419164
Sonoma         0.216973  0.149906  0.111628  ...  0.313361  0.344119  0.418106

[9 rows x 21 columns]

In [299]:
jobs_pivot=jobs_pivot.reset_index(drop=False)

In [300]:
len(jobs_pivot.columns)

22

In [328]:
tempcolumn=['County_Emp']+[x+y for x in ['U40k_','U50k_','U80k_'] for y in ['NaN','AGREMPN','FPSEMPN','HEREMPN','MWTEMPN','OTHEMPN','RETEMPN']]

In [309]:
print(tempcolumn)

['County_Emp', 'U40k_NaN', 'U40k_AGREMPN', 'U40k_FPSEMPN', 'U40k_HEREMPN', 'U40k_MWTEMPN', 'U40k_OTHEMPN', 'U40k_RETEMPN', 'U50k_NaN', 'U50k_AGREMPN', 'U50k_FPSEMPN', 'U50k_HEREMPN', 'U50k_MWTEMPN', 'U50k_OTHEMPN', 'U50k_RETEMPN', '80k_NaN', '80k_AGREMPN', '80k_FPSEMPN', '80k_HEREMPN', '80k_MWTEMPN', '80k_OTHEMPN', '80k_RETEMPN']

In [310]:
len(tempcolumn)

22

In [329]:
jobs_pivot.columns=tempcolumn

In [330]:
jobs_pivot

      County_Emp  U40k_NaN  ...  U80k_OTHEMPN  U80k_RETEMPN
0        Alameda  0.144467  ...      0.282801      0.348883
1   Contra Costa  0.137080  ...      0.288415      0.345878
2          Marin  0.063209  ...      0.291481      0.374490
3           Napa  0.000000  ...      0.321133      0.408079
4  San Francisco  0.122653  ...      0.206635      0.281152
5      San Mateo  0.083723  ...      0.178340      0.281970
6    Santa Clara  0.085836  ...      0.198401      0.303350
7         Solano  0.147287  ...      0.373042      0.419164
8         Sonoma  0.216973  ...      0.344119      0.418106

[9 rows x 22 columns]

In [199]:
juris15_shares = pd.merge(juris2015, jobs_pivot,  how='left', left_on=['County'], right_on = ['County_Emp'])
juris50_shares = pd.merge(juris2050, jobs_pivot,  how='left', left_on=['County'], right_on = ['County_Emp'])

NameError: name 'jobs_pivot' is not defined

In [378]:
#number of low wage jobs for each HH income cutoff
juris15_shares['LWJobs_U40k']=round(juris15_shares['U40k_AGREMPN']*juris15_shares['agrempn']+ \
                            juris15_shares['U40k_MWTEMPN']*juris15_shares['mwtempn']+ \
                            juris15_shares['U40k_RETEMPN']*juris15_shares['retempn']+ \
                            juris15_shares['U40k_FPSEMPN']*juris15_shares['fpsempn']+ \
                            juris15_shares['U40k_HEREMPN']*juris15_shares['herempn']+ \
                            juris15_shares['U40k_OTHEMPN']*juris15_shares['othempn'])

juris15_shares['LWJobs_U50k']=round(juris15_shares['U50k_AGREMPN']*juris15_shares['agrempn']+ \
                            juris15_shares['U50k_MWTEMPN']*juris15_shares['mwtempn']+ \
                            juris15_shares['U50k_RETEMPN']*juris15_shares['retempn']+ \
                            juris15_shares['U50k_FPSEMPN']*juris15_shares['fpsempn']+ \
                            juris15_shares['U50k_HEREMPN']*juris15_shares['herempn']+ \
                            juris15_shares['U50k_OTHEMPN']*juris15_shares['othempn'])

juris15_shares['LWJobs_U80k']=round(juris15_shares['U80k_AGREMPN']*juris15_shares['agrempn']+ \
                            juris15_shares['U80k_MWTEMPN']*juris15_shares['mwtempn']+ \
                            juris15_shares['U80k_RETEMPN']*juris15_shares['retempn']+ \
                            juris15_shares['U80k_FPSEMPN']*juris15_shares['fpsempn']+ \
                            juris15_shares['U80k_HEREMPN']*juris15_shares['herempn']+ \
                            juris15_shares['U80k_OTHEMPN']*juris15_shares['othempn'])

In [379]:
#Repeat for juris2050
#number of low wage jobs for each HH income cutoff
juris50_shares['LWJobs_U40k']=round(juris50_shares['U40k_AGREMPN']*juris50_shares['agrempn']+ \
                            juris50_shares['U40k_MWTEMPN']*juris50_shares['mwtempn']+ \
                            juris50_shares['U40k_RETEMPN']*juris50_shares['retempn']+ \
                            juris50_shares['U40k_FPSEMPN']*juris50_shares['fpsempn']+ \
                            juris50_shares['U40k_HEREMPN']*juris50_shares['herempn']+ \
                            juris50_shares['U40k_OTHEMPN']*juris50_shares['othempn'])

juris50_shares['LWJobs_U50k']=round(juris50_shares['U50k_AGREMPN']*juris50_shares['agrempn']+ \
                            juris50_shares['U50k_MWTEMPN']*juris50_shares['mwtempn']+ \
                            juris50_shares['U50k_RETEMPN']*juris50_shares['retempn']+ \
                            juris50_shares['U50k_FPSEMPN']*juris50_shares['fpsempn']+ \
                            juris50_shares['U50k_HEREMPN']*juris50_shares['herempn']+ \
                            juris50_shares['U50k_OTHEMPN']*juris50_shares['othempn'])

juris50_shares['LWJobs_U80k']=round(juris50_shares['U80k_AGREMPN']*juris50_shares['agrempn']+ \
                            juris50_shares['U80k_MWTEMPN']*juris50_shares['mwtempn']+ \
                            juris50_shares['U80k_RETEMPN']*juris50_shares['retempn']+ \
                            juris50_shares['U80k_FPSEMPN']*juris50_shares['fpsempn']+ \
                            juris50_shares['U80k_HEREMPN']*juris50_shares['herempn']+ \
                            juris50_shares['U80k_OTHEMPN']*juris50_shares['othempn'])

In [198]:
#Test Bay area J-HH fit 
#It should not be this low... .73
juris15_shares['LWJobs_U50k'].sum()/juris15_shares['hhincq1'].sum()

NameError: name 'juris15_shares' is not defined

In [381]:
#Test 2050 to see direction
#Even lower. Says there is more housing?
juris50_shares['LWJobs_U50k'].sum()/juris50_shares['hhincq1'].sum()

0.6060241891861139

In [383]:
#Test Bay area J-HH fit 
#Slightly higher if using Q1+Q2 and Under $80k annual HH income
juris15_shares['LWJobs_U80k'].sum()/(juris15_shares['hhincq1'].sum()+juris15_shares['hhincq2'].sum())

0.7976862323298941

In [384]:
# ~13% of all jobs are low wage
#this number also seems low
juris15_shares['LWJobs_U50k'].sum()/juris15_shares['totemp'].sum()

0.12873884170994662

In [385]:
juris50_shares['LWJobs_U50k'].sum()/juris50_shares['totemp'].sum()

0.12801777215695412

In [388]:
juris15_shares['Jobs-HH Fit']=juris15_shares['LWJobs_U50k']/juris15_shares['hhincq1']
juris50_shares['Jobs-HH Fit']=juris50_shares['LWJobs_U50k']/juris50_shares['hhincq1']

In [389]:
selected_columns = juris15_shares[["juris","County","Jobs-HH Fit",'LWJobs_U50k','totemp','hhincq1','tothh','U50k_AGREMPN','U50k_FPSEMPN','U50k_HEREMPN','U50k_MWTEMPN','U50k_OTHEMPN','U50k_RETEMPN']]
Juris15_export = selected_columns.copy()

In [390]:
selected_columns2 = juris50_shares[["juris","County","Jobs-HH Fit",'LWJobs_U50k','totemp','hhincq1','tothh','U50k_AGREMPN','U50k_FPSEMPN','U50k_HEREMPN','U50k_MWTEMPN','U50k_OTHEMPN','U50k_RETEMPN']]
Juris50_export = selected_columns2.copy()

In [391]:
Juris15_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\Jurisdiction2015_JHFit.csv', index = False)
Juris50_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\Jurisdiction2050_JHFit.csv', index = False)

In [392]:
county15_shares=juris15_shares.groupby("County").sum()
county50_shares=juris50_shares.groupby("County").sum()

In [393]:
county15_shares['Jobs-HH Fit']=county15_shares['LWJobs_U50k']/county15_shares['hhincq1']
county50_shares['Jobs-HH Fit']=county50_shares['LWJobs_U50k']/county50_shares['hhincq1']

In [394]:
#Note County is index
selected_columns = county15_shares[["Jobs-HH Fit",'LWJobs_U50k','totemp','hhincq1','tothh']]
County15_export = selected_columns.copy()
selected_columns2 = county50_shares[["Jobs-HH Fit",'LWJobs_U50k','totemp','hhincq1','tothh']]
County50_export = selected_columns2.copy()

In [395]:
County15_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\County2015_JHFit.csv')
County50_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\County2050_JHFit.csv')

In [396]:
County15_export

               Jobs-HH Fit  LWJobs_U50k   totemp  hhincq1   tothh
County
Alameda           0.700408     119042.0   815374   169961  553034
Contra Costa      0.596083      52286.0   373697    87716  382556
Marin             0.943979      18468.0   119652    19564  108935
Napa              0.900186      11634.0    63365    12924   50957
San Francisco     0.995983     118008.0   924982   118484  362220
San Mateo         0.741206      35440.0   349248    47814  267155
Santa Clara       0.648166     104111.0  1035571   160624  617732
Solano            0.657187      24032.0   124401    36568  143790
Sonoma            0.618006      32619.0   199028    52781  190197

In [397]:
County50_export

               Jobs-HH Fit  LWJobs_U50k   totemp  hhincq1    tothh
County
Alameda           0.532880     157748.0  1077336   296029   809109
Contra Costa      0.557690      67379.0   480389   120818   490191
Marin             0.604076      15857.0   106755    26250   141787
Napa              1.002299      16570.0    87675    16532    60111
San Francisco     1.304019     138981.0  1106908   106579   501148
San Mateo         0.689462      50965.0   493939    73920   404395
Santa Clara       0.482960     173618.0  1647169   359487  1177176
Solano            0.512380      31745.0   167816    61956   188513
Sonoma            0.488316      39516.0   240473    80923   270882

## Repeat for Earnings

In [113]:
earn_EB

,County_Emp,Industry,1_less than 30k,"2_30k to 39,999","3_40k to 49,999","4_50k to 79,999","5_80k to 99,999","6_100k to 149,999","7_150k to 249,999",8_250k+,tot_pwgt,shareLW_Under30k,shareLW_Under40k,shareLW_Under50k
0,Alameda,AGREMPN,1479,138,329,445,174,186,72,27,2850,0.518947,0.567368,0.682807
1,Alameda,FPSEMPN,44268,11611,11162,26941,15270,24819,14657,4468,153196,0.288963,0.364755,0.437616
2,Alameda,HEREMPN,120340,28599,23699,48282,17829,21175,9677,3598,273199,0.440485,0.545167,0.631913
3,Alameda,MWTEMPN,35805,16236,14354,34656,12477,19812,9998,3570,146908,0.243724,0.354242,0.451950
4,Alameda,NaN,2289,512,441,820,208,432,246,33,4981,0.459546,0.562337,0.650873
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
58,Sonoma,HEREMPN,46608,9740,7234,14182,4336,4339,1468,835,88742,0.525208,0.634964,0.716481
59,Sonoma,MWTEMPN,11235,4026,4340,9298,2614,3479,1784,787,37563,0.299098,0.406277,0.521817
60,Sonoma,NaN,693,68,57,238,14,20,40,13,1143,0.606299,0.665792,0.715661
61,Sonoma,OTHEMPN,9796,3274,3083,6844,2814,3046,1100,279,30236,0.323985,0.432266,0.534231
62,Sonoma,RETEMPN,16807,3957,2388,3014,658,601,439,112,27976,0.600765,0.742208,0.827566

In [114]:
#Before merging, need to pivot Industry from rows to columns
earn_EB.rename(inplace=True,columns={"shareLW_Under30k": "Under30k", "shareLW_Under40k": "Under40k","shareLW_Under50k": "Under50k"})
earn_pivot=earn_EB.pivot(index='County_Emp', columns='Industry', values=['Under30k','Under40k','Under50k'])

In [115]:
earn_pivot

               Under30k                                                    \
Industry            NaN   AGREMPN   FPSEMPN   HEREMPN   MWTEMPN   OTHEMPN
County_Emp
Alameda        0.459546  0.518947  0.288963  0.440485  0.243724  0.248460
Contra Costa   0.529412  0.461035  0.305870  0.492633  0.235548  0.276007
Marin          0.666126  0.631417  0.391711  0.491337  0.261903  0.259190
Napa           0.301418  0.565883  0.415765  0.487895  0.271080  0.329726
San Francisco  0.463830  0.551261  0.179497  0.390911  0.266310  0.197462
San Mateo      0.481539  0.677348  0.225675  0.458615  0.214988  0.207651
Santa Clara    0.430066  0.578947  0.222321  0.450630  0.143861  0.200098
Solano         0.598191  0.651843  0.468907  0.505246  0.299264  0.238870
Sonoma         0.606299  0.575175  0.429085  0.525208  0.299098  0.323985

                         Under40k                      ...            \
Industry        RETEMPN       NaN   AGREMPN   FPSEMPN  ...   MWTEMPN
County_Emp                                             ...
Alameda        0.504846  0.562337  0.567368  0.364755  ...  0.354242
Contra Costa   0.598640  0.627101  0.510808  0.381228  ...  0.311314
Marin          0.495497  0.734198  0.771047  0.438510  ...  0.340622
Napa           0.584123  0.500000  0.657007  0.522866  ...  0.381454
San Francisco  0.394243  0.538423  0.631777  0.229060  ...  0.350207
San Mateo      0.459893  0.663027  0.797063  0.274808  ...  0.310817
Santa Clara    0.510513  0.514637  0.713131  0.272406  ...  0.215898
Solano         0.687209  0.653747  0.807292  0.570599  ...  0.403843
Sonoma         0.600765  0.665792  0.741537  0.516417  ...  0.406277

                                   Under50k                                \
Industry        OTHEMPN   RETEMPN       NaN   AGREMPN   FPSEMPN   HEREMPN
County_Emp
Alameda        0.336994  0.628328  0.650873  0.682807  0.437616  0.631913
Contra Costa   0.352149  0.702350  0.706933  0.540102  0.454572  0.659663
Marin          0.329402  0.632881  0.734198  0.828542  0.505716  0.643504
Napa           0.452801  0.669308  0.673759  0.820120  0.612724  0.685076
San Francisco  0.253447  0.513036  0.632290  0.718196  0.278550  0.585593
San Mateo      0.267606  0.567259  0.756110  0.835336  0.326509  0.655294
Santa Clara    0.273611  0.611381  0.594541  0.774564  0.324741  0.631131
Solano         0.330340  0.767972  0.729974  0.828526  0.652119  0.679978
Sonoma         0.432266  0.742208  0.715661  0.816407  0.599824  0.716481


Industry        MWTEMPN   OTHEMPN   RETEMPN
County_Emp
Alameda        0.451950  0.423282  0.720596
Contra Costa   0.387160  0.443047  0.784278
Marin          0.420992  0.404078  0.735668
Napa           0.503180  0.534033  0.735673
San Francisco  0.416774  0.316900  0.597558
San Mateo      0.400948  0.334179  0.661713
Santa Clara    0.279839  0.340191  0.679987
Solano         0.522516  0.433595  0.830264
Sonoma         0.521817  0.534231  0.827566

[9 rows x 21 columns]

In [116]:
earn_pivot=earn_pivot.reset_index(drop=False)

In [117]:
len(earn_pivot.columns)

22

In [118]:
tempcolumn2=['County_Emp']+[x+y for x in ['U30k_','U40k_','U50k_'] for y in ['NaN','AGREMPN','FPSEMPN','HEREMPN','MWTEMPN','OTHEMPN','RETEMPN']]

In [119]:
print(tempcolumn2)

['County_Emp', 'U30k_NaN', 'U30k_AGREMPN', 'U30k_FPSEMPN', 'U30k_HEREMPN', 'U30k_MWTEMPN', 'U30k_OTHEMPN', 'U30k_RETEMPN', 'U40k_NaN', 'U40k_AGREMPN', 'U40k_FPSEMPN', 'U40k_HEREMPN', 'U40k_MWTEMPN', 'U40k_OTHEMPN', 'U40k_RETEMPN', 'U50k_NaN', 'U50k_AGREMPN', 'U50k_FPSEMPN', 'U50k_HEREMPN', 'U50k_MWTEMPN', 'U50k_OTHEMPN', 'U50k_RETEMPN']

In [120]:
len(tempcolumn2)

22

In [121]:
earn_pivot.columns=tempcolumn2

In [122]:
earn_pivot

,County_Emp,U30k_NaN,U30k_AGREMPN,U30k_FPSEMPN,U30k_HEREMPN,U30k_MWTEMPN,U30k_OTHEMPN,U30k_RETEMPN,U40k_NaN,U40k_AGREMPN,...,U40k_MWTEMPN,U40k_OTHEMPN,U40k_RETEMPN,U50k_NaN,U50k_AGREMPN,U50k_FPSEMPN,U50k_HEREMPN,U50k_MWTEMPN,U50k_OTHEMPN,U50k_RETEMPN
0,Alameda,0.459546,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846,0.562337,0.567368,...,0.354242,0.336994,0.628328,0.650873,0.682807,0.437616,0.631913,0.451950,0.423282,0.720596
1,Contra Costa,0.529412,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640,0.627101,0.510808,...,0.311314,0.352149,0.702350,0.706933,0.540102,0.454572,0.659663,0.387160,0.443047,0.784278
2,Marin,0.666126,0.631417,0.391711,0.491337,0.261903,0.259190,0.495497,0.734198,0.771047,...,0.340622,0.329402,0.632881,0.734198,0.828542,0.505716,0.643504,0.420992,0.404078,0.735668
3,Napa,0.301418,0.565883,0.415765,0.487895,0.271080,0.329726,0.584123,0.500000,0.657007,...,0.381454,0.452801,0.669308,0.673759,0.820120,0.612724,0.685076,0.503180,0.534033,0.735673
4,San Francisco,0.463830,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243,0.538423,0.631777,...,0.350207,0.253447,0.513036,0.632290,0.718196,0.278550,0.585593,0.416774,0.316900,0.597558
5,San Mateo,0.481539,0.677348,0.225675,0.458615,0.214988,0.207651,0.459893,0.663027,0.797063,...,0.310817,0.267606,0.567259,0.756110,0.835336,0.326509,0.655294,0.400948,0.334179,0.661713
6,Santa Clara,0.430066,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513,0.514637,0.713131,...,0.215898,0.273611,0.611381,0.594541,0.774564,0.324741,0.631131,0.279839,0.340191,0.679987
7,Solano,0.598191,0.651843,0.468907,0.505246,0.299264,0.238870,0.687209,0.653747,0.807292,...,0.403843,0.330340,0.767972,0.729974,0.828526,0.652119,0.679978,0.522516,0.433595,0.830264
8,Sonoma,0.606299,0.575175,0.429085,0.525208,0.299098,0.323985,0.600765,0.665792,0.741537,...,0.406277,0.432266,0.742208,0.715661,0.816407,0.599824,0.716481,0.521817,0.534231,0.827566

First apply to jurisdictions then super districts

In [123]:
juris15_Eshares = pd.merge(juris2015, earn_pivot,  how='left', left_on=['County'], right_on = ['County_Emp'])
juris50_Eshares = pd.merge(juris2050, earn_pivot,  how='left', left_on=['County'], right_on = ['County_Emp'])

In [126]:
#number of low wage jobs for each HH income cutoff
juris15_Eshares['LWJobs_U30k']=round(juris15_Eshares['U30k_AGREMPN']*juris15_Eshares['AGREMPN']+ \
                            juris15_Eshares['U30k_MWTEMPN']*juris15_Eshares['MWTEMPN']+ \
                            juris15_Eshares['U30k_RETEMPN']*juris15_Eshares['RETEMPN']+ \
                            juris15_Eshares['U30k_FPSEMPN']*juris15_Eshares['FPSEMPN']+ \
                            juris15_Eshares['U30k_HEREMPN']*juris15_Eshares['HEREMPN']+ \
                            juris15_Eshares['U30k_OTHEMPN']*juris15_Eshares['OTHEMPN'])

juris15_Eshares['LWJobs_U40k']=round(juris15_Eshares['U40k_AGREMPN']*juris15_Eshares['AGREMPN']+ \
                            juris15_Eshares['U40k_MWTEMPN']*juris15_Eshares['MWTEMPN']+ \
                            juris15_Eshares['U40k_RETEMPN']*juris15_Eshares['RETEMPN']+ \
                            juris15_Eshares['U40k_FPSEMPN']*juris15_Eshares['FPSEMPN']+ \
                            juris15_Eshares['U40k_HEREMPN']*juris15_Eshares['HEREMPN']+ \
                            juris15_Eshares['U40k_OTHEMPN']*juris15_Eshares['OTHEMPN'])

juris15_Eshares['LWJobs_U50k']=round(juris15_Eshares['U50k_AGREMPN']*juris15_Eshares['AGREMPN']+ \
                            juris15_Eshares['U50k_MWTEMPN']*juris15_Eshares['MWTEMPN']+ \
                            juris15_Eshares['U50k_RETEMPN']*juris15_Eshares['RETEMPN']+ \
                            juris15_Eshares['U50k_FPSEMPN']*juris15_Eshares['FPSEMPN']+ \
                            juris15_Eshares['U50k_HEREMPN']*juris15_Eshares['HEREMPN']+ \
                            juris15_Eshares['U50k_OTHEMPN']*juris15_Eshares['OTHEMPN'])

In [127]:
#Repeat for juris2050
#number of low wage jobs for each HH income cutoff
juris50_Eshares['LWJobs_U30k']=round(juris50_Eshares['U30k_AGREMPN']*juris50_Eshares['AGREMPN']+ \
                            juris50_Eshares['U30k_MWTEMPN']*juris50_Eshares['MWTEMPN']+ \
                            juris50_Eshares['U30k_RETEMPN']*juris50_Eshares['RETEMPN']+ \
                            juris50_Eshares['U30k_FPSEMPN']*juris50_Eshares['FPSEMPN']+ \
                            juris50_Eshares['U30k_HEREMPN']*juris50_Eshares['HEREMPN']+ \
                            juris50_Eshares['U30k_OTHEMPN']*juris50_Eshares['OTHEMPN'])

juris50_Eshares['LWJobs_U40k']=round(juris50_Eshares['U40k_AGREMPN']*juris50_Eshares['AGREMPN']+ \
                            juris50_Eshares['U40k_MWTEMPN']*juris50_Eshares['MWTEMPN']+ \
                            juris50_Eshares['U40k_RETEMPN']*juris50_Eshares['RETEMPN']+ \
                            juris50_Eshares['U40k_FPSEMPN']*juris50_Eshares['FPSEMPN']+ \
                            juris50_Eshares['U40k_HEREMPN']*juris50_Eshares['HEREMPN']+ \
                            juris50_Eshares['U40k_OTHEMPN']*juris50_Eshares['OTHEMPN'])

juris50_Eshares['LWJobs_U50k']=round(juris50_Eshares['U50k_AGREMPN']*juris50_Eshares['AGREMPN']+ \
                            juris50_Eshares['U50k_MWTEMPN']*juris50_Eshares['MWTEMPN']+ \
                            juris50_Eshares['U50k_RETEMPN']*juris50_Eshares['RETEMPN']+ \
                            juris50_Eshares['U50k_FPSEMPN']*juris50_Eshares['FPSEMPN']+ \
                            juris50_Eshares['U50k_HEREMPN']*juris50_Eshares['HEREMPN']+ \
                            juris50_Eshares['U50k_OTHEMPN']*juris50_Eshares['OTHEMPN'])

In [134]:
#Test Bay area J-HH fit 
#That's more like it! ~1.85 if 30k, ~2.3 if 40k
juris15_Eshares['LWJobs_U40k'].sum()/juris15_Eshares['hhincq1'].sum()

2.328021222021528

In [137]:
#Test 2050 to see direction
#1.56 if 30k, 1.95 if 40k
juris50_Eshares['LWJobs_U40k'].sum()/juris50_Eshares['hhincq1'].sum()

1.9576487929039452

In [139]:
# ~41% of all jobs are low wage ($40k,33% $30k) 
#this number also seems low
juris15_Eshares['LWJobs_U30k'].sum()/juris15_Eshares['totemp'].sum()

0.3263046779306911

In [202]:
#only a tiny shift, .3%
juris50_Eshares['LWJobs_U30k'].sum()/juris50_Eshares['totemp'].sum()

0.3296376417686365

In [188]:
juris15_Eshares['Jobs-HH Fit']=juris15_Eshares['LWJobs_U30k']/juris15_Eshares['hhincq1']
juris50_Eshares['Jobs-HH Fit']=juris50_Eshares['LWJobs_U30k']/juris50_Eshares['hhincq1']

In [189]:
selected_columns = juris15_Eshares[["juris","County","Jobs-HH Fit",'LWJobs_U30k','totemp','hhincq1','tothh','U30k_AGREMPN','U30k_FPSEMPN','U30k_HEREMPN','U30k_MWTEMPN','U30k_OTHEMPN','U30k_RETEMPN']]
Juris15_Earn_export = selected_columns.copy()

In [190]:
selected_columns2 = juris50_Eshares[["juris","County","Jobs-HH Fit",'LWJobs_U30k','totemp','hhincq1','tothh','U30k_AGREMPN','U30k_FPSEMPN','U30k_HEREMPN','U30k_MWTEMPN','U30k_OTHEMPN','U30k_RETEMPN']]
Juris50_Earn_export = selected_columns2.copy()

In [145]:
#Juris15_Earn_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\Jurisdiction2015_JHFit_Earnings.csv', index = False)
#Juris50_Earn_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\Jurisdiction2050_JHFit_Earnings.csv', index = False)

In [191]:
#Add suffix for years
Juris15_Earn_export=Juris15_Earn_export.add_suffix('_2015')
Juris50_Earn_export=Juris50_Earn_export.add_suffix('_2050')

In [192]:
Juris_Earn_results = pd.merge(Juris15_Earn_export, Juris50_Earn_export,  how='left', left_on=['juris_2015'], right_on = ['juris_2050'])

In [193]:
Juris_Earn_results

,juris_2015,County_2015,Jobs-HH Fit_2015,LWJobs_U30k_2015,totemp_2015,hhincq1_2015,tothh_2015,U30k_AGREMPN_2015,U30k_FPSEMPN_2015,U30k_HEREMPN_2015,...,LWJobs_U30k_2050,totemp_2050,hhincq1_2050,tothh_2050,U30k_AGREMPN_2050,U30k_FPSEMPN_2050,U30k_HEREMPN_2050,U30k_MWTEMPN_2050,U30k_OTHEMPN_2050,U30k_RETEMPN_2050
0,Alameda,Alameda,1.256370,11242.0,31856,8948,30148,0.518947,0.288963,0.440485,...,17121.0,49134,11042,40173,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
1,Alameda County,Alameda,0.611506,8078.0,23613,13210,49403,0.518947,0.288963,0.440485,...,13355.0,35510,13402,54478,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
2,Albany,Alameda,0.705622,1594.0,4453,2259,7435,0.518947,0.288963,0.440485,...,1791.0,5090,1848,8535,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
3,American Canyon,Napa,1.813078,2745.0,6250,1514,5540,0.565883,0.415765,0.487895,...,5510.0,12548,2237,7680,0.565883,0.415765,0.487895,0.271080,0.329726,0.584123
4,Antioch,Contra Costa,1.156706,8961.0,21888,7747,32856,0.461035,0.305870,0.492633,...,12094.0,28559,12032,41743,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
104,Vallejo,Solano,1.041960,12292.0,28048,11797,41571,0.651843,0.468907,0.505246,...,16180.0,35672,14002,48130,0.651843,0.468907,0.505246,0.299264,0.238870,0.687209
105,Walnut Creek,Contra Costa,2.484235,18515.0,50440,7453,31050,0.461035,0.305870,0.492633,...,21145.0,54673,8671,45190,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
106,Windsor,Sonoma,1.602539,3282.0,7226,2048,9017,0.575175,0.429085,0.525208,...,4515.0,9731,3273,11446,0.575175,0.429085,0.525208,0.299098,0.323985,0.600765
107,Woodside,San Mateo,3.684564,549.0,1788,149,2217,0.677348,0.225675,0.458615,...,719.0,2238,443,2297,0.677348,0.225675,0.458615,0.214988,0.207651,0.459893
108,Yountville,Napa,3.176471,1026.0,2167,323,1141,0.565883,0.415765,0.487895,...,1503.0,3195,364,1261,0.565883,0.415765,0.487895,0.271080,0.329726,0.584123

In [195]:
Juris_Earn_results['cLWJobs']=Juris_Earn_results['LWJobs_U30k_2050']-Juris_Earn_results['LWJobs_U30k_2015']
Juris_Earn_results['cpctLWJobs']=Juris_Earn_results['LWJobs_U30k_2050']/Juris_Earn_results['totemp_2050']-Juris_Earn_results['LWJobs_U30k_2015']/Juris_Earn_results['totemp_2015']
Juris_Earn_results['chhq1']=Juris_Earn_results['hhincq1_2050']-Juris_Earn_results['hhincq1_2015']
Juris_Earn_results['cpcthhq1']=Juris_Earn_results['hhincq1_2050']/Juris_Earn_results['totemp_2050']-Juris_Earn_results['hhincq1_2015']/Juris_Earn_results['totemp_2015']
Juris_Earn_results['cJHFit']=Juris_Earn_results['Jobs-HH Fit_2050']-Juris_Earn_results['Jobs-HH Fit_2015']
Juris_Earn_results['JHFitcto1']=abs(Juris_Earn_results['Jobs-HH Fit_2050']-1)<abs(Juris_Earn_results['Jobs-HH Fit_2015']-1)

In [196]:
Juris_Earn_results.rename({'juris_2015': 'juris', 'County_2015': 'County'}, axis=1, inplace=True)
selected_columns = Juris_Earn_results[["juris","County","Jobs-HH Fit_2015","Jobs-HH Fit_2050",'cJHFit','JHFitcto1','LWJobs_U40k_2015','cLWJobs','cpctLWJobs','hhincq1_2015','chhq1','cpcthhq1']]
Juris_Earn_select = selected_columns.copy()

KeyError: "['LWJobs_U40k_2015'] not in index"

In [151]:
#71 out of 108 juris (including unincorporated) have JH Fit closer to 1
Juris_Earn_select['JHFitcto1'].sum()

70

In [152]:
Juris_Earn_select

,juris,County,Jobs-HH Fit_2015,Jobs-HH Fit_2050,cJHFit,JHFitcto1,LWJobs_U40k_2015,cLWJobs,cpctLWJobs,hhincq1_2015,chhq1,cpcthhq1
0,Alameda,Alameda,1.605498,1.973737,0.368238,False,14366.0,7428.0,-0.007404,8948,2094,-0.056157
1,Alameda County,Alameda,0.788115,1.257573,0.469458,False,10411.0,6443.0,0.033726,13210,192,-0.182023
2,Albany,Alameda,0.900398,1.233225,0.332827,False,2034.0,245.0,-0.009030,2259,-411,-0.144234
3,American Canyon,Napa,2.262219,3.076442,0.814222,False,3425.0,3457.0,0.000454,1514,723,-0.063965
4,Antioch,Contra Costa,1.405447,1.215758,-0.189689,True,10888.0,3740.0,0.014761,7747,4285,0.067365
...,...,...,...,...,...,...,...,...,...,...,...,...
104,Vallejo,Solano,1.261846,1.393872,0.132026,False,14886.0,4631.0,0.016391,11797,2205,-0.028080
105,Walnut Creek,Contra Costa,3.056756,2.978665,-0.078091,True,22782.0,3046.0,0.020743,7453,1218,0.010838
106,Windsor,Sonoma,1.991699,1.703025,-0.288674,True,4079.0,1495.0,0.008319,2048,1225,0.052927
107,Woodside,San Mateo,4.704698,2.063205,-2.641493,True,701.0,213.0,0.016342,149,294,0.114611
108,Yountville,Napa,3.869969,5.074176,1.204207,False,1250.0,597.0,0.001256,323,41,-0.035126

In [197]:
selected_columnsTBL = Juris_Earn_results[["juris","County","Jobs-HH Fit_2015","Jobs-HH Fit_2050",'cJHFit','JHFitcto1','LWJobs_U30k_2015','totemp_2015','hhincq1_2015','tothh_2015','LWJobs_U30k_2050','totemp_2050','hhincq1_2050','tothh_2050']]
Juris_Earn_Tableau = selected_columnsTBL.copy()

In [203]:
Juris_Earn_Tableau.to_csv('/Users/jeremyhalpern/Desktop/JHFit/Output/Juris_JHFit_earnings.csv', index = False)

## Repeat for superdistrict

In [155]:
SD15_Eshares = pd.merge(SD2015, earn_pivot,  how='left', left_on=['County'], right_on = ['County_Emp'])
SD50_Eshares = pd.merge(SD2050, earn_pivot,  how='left', left_on=['County'], right_on = ['County_Emp'])

In [156]:
#number of low wage jobs for each HH income cutoff
SD15_Eshares['LWJobs_U30k']=round(SD15_Eshares['U30k_AGREMPN']*SD15_Eshares['AGREMPN']+ \
                            SD15_Eshares['U30k_MWTEMPN']*SD15_Eshares['MWTEMPN']+ \
                            SD15_Eshares['U30k_RETEMPN']*SD15_Eshares['RETEMPN']+ \
                            SD15_Eshares['U30k_FPSEMPN']*SD15_Eshares['FPSEMPN']+ \
                            SD15_Eshares['U30k_HEREMPN']*SD15_Eshares['HEREMPN']+ \
                            SD15_Eshares['U30k_OTHEMPN']*SD15_Eshares['OTHEMPN'])

SD15_Eshares['LWJobs_U40k']=round(SD15_Eshares['U40k_AGREMPN']*SD15_Eshares['AGREMPN']+ \
                            SD15_Eshares['U40k_MWTEMPN']*SD15_Eshares['MWTEMPN']+ \
                            SD15_Eshares['U40k_RETEMPN']*SD15_Eshares['RETEMPN']+ \
                            SD15_Eshares['U40k_FPSEMPN']*SD15_Eshares['FPSEMPN']+ \
                            SD15_Eshares['U40k_HEREMPN']*SD15_Eshares['HEREMPN']+ \
                            SD15_Eshares['U40k_OTHEMPN']*SD15_Eshares['OTHEMPN'])

SD15_Eshares['LWJobs_U50k']=round(SD15_Eshares['U50k_AGREMPN']*SD15_Eshares['AGREMPN']+ \
                            SD15_Eshares['U50k_MWTEMPN']*SD15_Eshares['MWTEMPN']+ \
                            SD15_Eshares['U50k_RETEMPN']*SD15_Eshares['RETEMPN']+ \
                            SD15_Eshares['U50k_FPSEMPN']*SD15_Eshares['FPSEMPN']+ \
                            SD15_Eshares['U50k_HEREMPN']*SD15_Eshares['HEREMPN']+ \
                            SD15_Eshares['U50k_OTHEMPN']*SD15_Eshares['OTHEMPN'])

In [157]:
#Repeat for SD2050
#number of low wage jobs for each HH income cutoff
SD50_Eshares['LWJobs_U30k']=round(SD50_Eshares['U30k_AGREMPN']*SD50_Eshares['AGREMPN']+ \
                            SD50_Eshares['U30k_MWTEMPN']*SD50_Eshares['MWTEMPN']+ \
                            SD50_Eshares['U30k_RETEMPN']*SD50_Eshares['RETEMPN']+ \
                            SD50_Eshares['U30k_FPSEMPN']*SD50_Eshares['FPSEMPN']+ \
                            SD50_Eshares['U30k_HEREMPN']*SD50_Eshares['HEREMPN']+ \
                            SD50_Eshares['U30k_OTHEMPN']*SD50_Eshares['OTHEMPN'])

SD50_Eshares['LWJobs_U40k']=round(SD50_Eshares['U40k_AGREMPN']*SD50_Eshares['AGREMPN']+ \
                            SD50_Eshares['U40k_MWTEMPN']*SD50_Eshares['MWTEMPN']+ \
                            SD50_Eshares['U40k_RETEMPN']*SD50_Eshares['RETEMPN']+ \
                            SD50_Eshares['U40k_FPSEMPN']*SD50_Eshares['FPSEMPN']+ \
                            SD50_Eshares['U40k_HEREMPN']*SD50_Eshares['HEREMPN']+ \
                            SD50_Eshares['U40k_OTHEMPN']*SD50_Eshares['OTHEMPN'])

SD50_Eshares['LWJobs_U50k']=round(SD50_Eshares['U50k_AGREMPN']*SD50_Eshares['AGREMPN']+ \
                            SD50_Eshares['U50k_MWTEMPN']*SD50_Eshares['MWTEMPN']+ \
                            SD50_Eshares['U50k_RETEMPN']*SD50_Eshares['RETEMPN']+ \
                            SD50_Eshares['U50k_FPSEMPN']*SD50_Eshares['FPSEMPN']+ \
                            SD50_Eshares['U50k_HEREMPN']*SD50_Eshares['HEREMPN']+ \
                            SD50_Eshares['U50k_OTHEMPN']*SD50_Eshares['OTHEMPN'])

In [161]:
#Test Bay area J-HH fit 
#That's more like it! ~1.85 if 30k, ~2.3 if 40k
SD15_Eshares['LWJobs_U30k'].sum()/SD15_Eshares['hhincq1'].sum()

1.8523999343181832

In [162]:
#Test 2050 to see direction
#1.56 if 30k, 1.95 if 40k
SD50_Eshares['LWJobs_U30k'].sum()/SD50_Eshares['hhincq1'].sum()

1.560974499647263

In [163]:
# ~41% of all jobs are low wage ($40k,33% $30k) 
#this number also seems low
SD15_Eshares['LWJobs_U30k'].sum()/SD15_Eshares['totemp'].sum()

0.3267161309039632

In [165]:
#only a tiny shift, .3%
SD50_Eshares['LWJobs_U30k'].sum()/SD50_Eshares['totemp'].sum()

0.3297434020035278

In [167]:
SD15_Eshares['Jobs-HH Fit']=SD15_Eshares['LWJobs_U30k']/SD15_Eshares['hhincq1']
SD50_Eshares['Jobs-HH Fit']=SD50_Eshares['LWJobs_U30k']/SD50_Eshares['hhincq1']

In [171]:
list(SD15_Eshares.columns)

['superdistrict',
 'tothh',
 'hhincq1',
 'hhincq2',
 'hhincq3',
 'hhincq4',
 'sfdu',
 'mfdu',
 'totemp',
 'AGREMPN',
 'FPSEMPN',
 'HEREMPN',
 'MWTEMPN',
 'OTHEMPN',
 'RETEMPN',
 'occupancy_rate',
 'non_residential_sqft',
 'sq_ft_per_employee',
 'deed_restricted_units',
 'inclusionary_units',
 'subsidized_units',
 'inclusionary_revenue_reduction',
 'inclusionary_revenue_reduction_per_unit',
 'total_subsidy',
 'subsidy_per_unit',
 'fip_co',
 'County',
 'SD_ID',
 'SD_NAME',
 'County_Emp',
 'U30k_NaN',
 'U30k_AGREMPN',
 'U30k_FPSEMPN',
 'U30k_HEREMPN',
 'U30k_MWTEMPN',
 'U30k_OTHEMPN',
 'U30k_RETEMPN',
 'U40k_NaN',
 'U40k_AGREMPN',
 'U40k_FPSEMPN',
 'U40k_HEREMPN',
 'U40k_MWTEMPN',
 'U40k_OTHEMPN',
 'U40k_RETEMPN',
 'U50k_NaN',
 'U50k_AGREMPN',
 'U50k_FPSEMPN',
 'U50k_HEREMPN',
 'U50k_MWTEMPN',
 'U50k_OTHEMPN',
 'U50k_RETEMPN',
 'LWJobs_U30k',
 'LWJobs_U40k',
 'LWJobs_U50k',
 'Jobs-HH Fit']

In [173]:
SD15_Earn_export

,SD_NAME,County,Jobs-HH Fit,LWJobs_U30k,totemp,hhincq1,tothh,U30k_AGREMPN,U30k_FPSEMPN,U30k_HEREMPN,U30k_MWTEMPN,U30k_OTHEMPN,U30k_RETEMPN
0,Greater Downtown San Francisco,San Francisco,3.516182,145257.0,503985,41311,82670,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243
1,Richmond District,San Francisco,0.816456,26325.0,89131,32243,107651,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243
2,Mission District,San Francisco,2.557606,83002.0,299990,32453,120451,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243
3,Sunset District,San Francisco,0.766063,9562.0,31876,12482,51482,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243
4,Daly City/San Bruno,San Mateo,1.870981,35268.0,118738,18850,98467,0.677348,0.225675,0.458615,0.214988,0.207651,0.459893
5,San Mateo/Burlingame,San Mateo,1.954947,28769.0,95022,14716,88177,0.677348,0.225675,0.458615,0.214988,0.207651,0.459893
6,Redwood City/Menlo Park,San Mateo,2.809042,40012.0,135488,14244,80473,0.677348,0.225675,0.458615,0.214988,0.207651,0.459893
7,Palo Alto/Los Altos,Santa Clara,2.572732,43721.0,160895,16994,74044,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
8,Sunnyvale/Mountain View,Santa Clara,3.121111,95403.0,367252,30567,104278,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
9,Cupertino/Saratoga,Santa Clara,1.486123,41766.0,133415,28104,121282,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
10,Central San Jose,Santa Clara,1.438081,52907.0,165741,36790,103878,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
11,Milpitas/East San Jose,Santa Clara,1.323834,33076.0,109260,24985,107570,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
12,South San Jose,Santa Clara,1.045220,15810.0,51215,15126,72909,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
13,Gilroy/Morgan Hill,Santa Clara,1.931086,15636.0,47797,8097,33886,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
14,Livermore/Pleasanton,Alameda,3.737470,43549.0,123809,11652,71852,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
15,Fremont/Union City,Alameda,2.036157,45502.0,137743,22347,105633,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
16,Hayward/San Leandro,Alameda,1.395180,50419.0,148251,36138,122047,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
17,Oakland/Alameda,Alameda,1.258248,92451.0,263784,73476,179808,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
18,Berkeley/Albany,Alameda,1.791160,47129.0,141903,26312,73559,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
19,Richmond/El Cerrito,Contra Costa,1.060998,29361.0,75651,27673,89524,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
20,Concord/Martinez,Contra Costa,2.091181,43277.0,110346,20695,85687,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
21,Walnut Creek,Contra Costa,2.380690,27197.0,74150,11424,60323,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
22,Danville/San Ramon,Contra Costa,4.122969,23604.0,60893,5725,54100,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
23,Antioch/Pittsburg,Contra Costa,0.959544,21299.0,52537,22197,92948,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
24,Vallejo/Benicia,Solano,1.333097,18778.0,42108,14086,53073,0.651843,0.468907,0.505246,0.299264,0.238870,0.687209
25,Fairfield/Vacaville,Solano,1.670555,37524.0,82288,22462,90647,0.651843,0.468907,0.505246,0.299264,0.238870,0.687209
26,Napa,Napa,2.031342,18731.0,43922,9221,34658,0.565883,0.415765,0.487895,0.271080,0.329726,0.584123
27,Saint Helena,Napa,2.340048,8712.0,19448,3723,16367,0.565883,0.415765,0.487895,0.271080,0.329726,0.584123
28,Petaluma/Rohnert Park,Sonoma,1.730854,29042.0,65498,16779,65047,0.575175,0.429085,0.525208,0.299098,0.323985,0.600765
29,Santa Rosa/Sebastopol,Sonoma,1.849712,47545.0,106645,25704,88836,0.575175,0.429085,0.525208,0.299098,0.323985,0.600765
30,Healdsburg/Cloverdale,Sonoma,1.198951,12348.0,26885,10299,36317,0.575175,0.429085,0.525208,0.299098,0.323985,0.600765
31,Novato,Marin,2.107088,9602.0,25926,4557,23202,0.631417,0.391711,0.491337,0.261903,0.259190,0.495497
32,San Rafael,Marin,2.312059,21627.0,55554,9354,44231,0.631417,0.391711,0.491337,0.261903,0.259190,0.495497
33,Mill Valley/Sausalito,Marin,2.547080,14391.0,38172,5650,41499,0.631417,0.391711,0.491337,0.261903,0.259190,0.495497

In [174]:
selected_columns = SD15_Eshares[["SD_ID","SD_NAME","County","Jobs-HH Fit",'LWJobs_U30k','totemp','hhincq1','tothh','U30k_AGREMPN','U30k_FPSEMPN','U30k_HEREMPN','U30k_MWTEMPN','U30k_OTHEMPN','U30k_RETEMPN']]
SD15_Earn_export = selected_columns.copy()

In [176]:
selected_columns2 = SD50_Eshares[["SD_ID","SD_NAME","County","Jobs-HH Fit",'LWJobs_U30k','totemp','hhincq1','tothh','U30k_AGREMPN','U30k_FPSEMPN','U30k_HEREMPN','U30k_MWTEMPN','U30k_OTHEMPN','U30k_RETEMPN']]
SD50_Earn_export = selected_columns2.copy()

In [145]:
#Juris15_Earn_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\Jurisdiction2015_JHFit_Earnings.csv', index = False)
#Juris50_Earn_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\Jurisdiction2050_JHFit_Earnings.csv', index = False)

In [177]:
#Add suffix for years
SD15_Earn_export=SD15_Earn_export.add_suffix('_2015')
SD50_Earn_export=SD50_Earn_export.add_suffix('_2050')

In [178]:
SD_Earn_results = pd.merge(SD15_Earn_export, SD50_Earn_export,  how='left', left_on=['SD_NAME_2015'], right_on = ['SD_NAME_2050'])

In [179]:
SD_Earn_results

,SD_ID_2015,SD_NAME_2015,County_2015,Jobs-HH Fit_2015,LWJobs_U30k_2015,totemp_2015,hhincq1_2015,tothh_2015,U30k_AGREMPN_2015,U30k_FPSEMPN_2015,...,LWJobs_U30k_2050,totemp_2050,hhincq1_2050,tothh_2050,U30k_AGREMPN_2050,U30k_FPSEMPN_2050,U30k_HEREMPN_2050,U30k_MWTEMPN_2050,U30k_OTHEMPN_2050,U30k_RETEMPN_2050
0,1,Greater Downtown San Francisco,San Francisco,3.516182,145257.0,503985,41311,82670,0.551261,0.179497,...,164797.0,577947,36417,125543,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243
1,2,Richmond District,San Francisco,0.816456,26325.0,89131,32243,107651,0.551261,0.179497,...,31364.0,102778,29709,124516,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243
2,3,Mission District,San Francisco,2.557606,83002.0,299990,32453,120451,0.551261,0.179497,...,107015.0,388571,30445,189415,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243
3,4,Sunset District,San Francisco,0.766063,9562.0,31876,12482,51482,0.551261,0.179497,...,11492.0,37609,10015,61708,0.551261,0.179497,0.390911,0.266310,0.197462,0.394243
4,5,Daly City/San Bruno,San Mateo,1.870981,35268.0,118738,18850,98467,0.677348,0.225675,...,64986.0,206285,30926,174961,0.677348,0.225675,0.458615,0.214988,0.207651,0.459893
5,6,San Mateo/Burlingame,San Mateo,1.954947,28769.0,95022,14716,88177,0.677348,0.225675,...,32329.0,108146,20525,116652,0.677348,0.225675,0.458615,0.214988,0.207651,0.459893
6,7,Redwood City/Menlo Park,San Mateo,2.809042,40012.0,135488,14244,80473,0.677348,0.225675,...,52323.0,179511,22463,112744,0.677348,0.225675,0.458615,0.214988,0.207651,0.459893
7,8,Palo Alto/Los Altos,Santa Clara,2.572732,43721.0,160895,16994,74044,0.578947,0.222321,...,47443.0,168404,33816,135437,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
8,9,Sunnyvale/Mountain View,Santa Clara,3.121111,95403.0,367252,30567,104278,0.578947,0.222321,...,222085.0,790055,85204,263064,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
9,10,Cupertino/Saratoga,Santa Clara,1.486123,41766.0,133415,28104,121282,0.578947,0.222321,...,51729.0,163510,50480,202492,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
10,11,Central San Jose,Santa Clara,1.438081,52907.0,165741,36790,103878,0.578947,0.222321,...,85770.0,271304,83613,220864,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
11,12,Milpitas/East San Jose,Santa Clara,1.323834,33076.0,109260,24985,107570,0.578947,0.222321,...,40538.0,125169,59438,200947,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
12,13,South San Jose,Santa Clara,1.045220,15810.0,51215,15126,72909,0.578947,0.222321,...,24606.0,72826,28610,100898,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
13,14,Gilroy/Morgan Hill,Santa Clara,1.931086,15636.0,47797,8097,33886,0.578947,0.222321,...,18386.0,55901,18334,53527,0.578947,0.222321,0.450630,0.143861,0.200098,0.510513
14,15,Livermore/Pleasanton,Alameda,3.737470,43549.0,123809,11652,71852,0.518947,0.288963,...,55103.0,154483,27863,113379,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
15,16,Fremont/Union City,Alameda,2.036157,45502.0,137743,22347,105633,0.518947,0.288963,...,77678.0,229072,43502,160398,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
16,17,Hayward/San Leandro,Alameda,1.395180,50419.0,148251,36138,122047,0.518947,0.288963,...,76594.0,221943,35832,144286,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
17,18,Oakland/Alameda,Alameda,1.258248,92451.0,263784,73476,179808,0.518947,0.288963,...,107907.0,316135,155438,289935,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
18,19,Berkeley/Albany,Alameda,1.791160,47129.0,141903,26312,73559,0.518947,0.288963,...,51318.0,155703,33396,101100,0.518947,0.288963,0.440485,0.243724,0.248460,0.504846
19,20,Richmond/El Cerrito,Contra Costa,1.060998,29361.0,75651,27673,89524,0.461035,0.305870,...,45507.0,118174,33591,120329,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
20,21,Concord/Martinez,Contra Costa,2.091181,43277.0,110346,20695,85687,0.461035,0.305870,...,59225.0,150711,26081,102043,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
21,22,Walnut Creek,Contra Costa,2.380690,27197.0,74150,11424,60323,0.461035,0.305870,...,29969.0,77637,15479,81335,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
22,23,Danville/San Ramon,Contra Costa,4.122969,23604.0,60893,5725,54100,0.461035,0.305870,...,24901.0,62000,12480,65800,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
23,24,Antioch/Pittsburg,Contra Costa,0.959544,21299.0,52537,22197,92948,0.461035,0.305870,...,30302.0,71867,33178,120648,0.461035,0.305870,0.492633,0.235548,0.276007,0.598640
24,25,Vallejo/Benicia,Solano,1.333097,18778.0,42108,14086,53073,0.651843,0.468907,...,24794.0,54209,17240,60809,0.651843,0.468907,0.505246,0.299264,0.238870,0.687209
25,26,Fairfield/Vacaville,Solano,1.670555,37524.0,82288,22462,90647,0.651843,0.468907,...,53009.0,113595,44701,127626,0.651843,0.468907,0.505246,0.299264,0.238870,0.687209
26,27,Napa,Napa,2.031342,18731.0,43922,9221,34658,0.565883,0.415765,...,27868.0,62798,11652,41864,0.565883,0.415765,0.487895,0.271080,0.329726,0.584123
27,28,Saint Helena,Napa,2.340048,8712.0,19448,3723,16367,0.565883,0.415765,...,11597.0,24889,4895,18323,0.565883,0.415765,0.487895,0.271080,0.329726,0.584123
28,29,Petaluma/Rohnert Park,Sonoma,1.730854,29042.0,65498,16779,65047,0.575175,0.429085,...,35996.0,78693,22887,85125,0.575175,0.429085,0.525208,0.299098,0.323985,0.600765
29,30,Santa Rosa/Sebastopol,Sonoma,1.849712,47545.0,106645,25704,88836,0.575175,0.429085,...,56372.0,121875,44266,141608,0.575175,0.429085,0.525208,0.299098,0.323985,0.600765
30,31,Healdsburg/Cloverdale,Sonoma,1.198951,12348.0,26885,10299,36317,0.575175,0.429085,...,18833.0,39905,13770,44152,0.575175,0.429085,0.525208,0.299098,0.323985,0.600765
31,32,Novato,Marin,2.107088,9602.0,25926,4557,23202,0.631417,0.391711,...,11805.0,30836,6087,32134,0.631417,0.391711,0.491337,0.261903,0.259190,0.495497
32,33,San Rafael,Marin,2.312059,21627.0,55554,9354,44231,0.631417,0.391711,...,16109.0,40907,11570,60692,0.631417,0.391711,0.491337,0.261903,0.259190,0.495497
33,34,Mill Valley/Sausalito,Marin,2.547080,14391.0,38172,5650,41499,0.631417,0.391711,...,13654.0,35012,8591,48958,0.631417,0.391711,0.491337,0.261903,0.259190,0.495497

In [180]:
SD_Earn_results['cLWJobs']=SD_Earn_results['LWJobs_U30k_2050']-SD_Earn_results['LWJobs_U30k_2015']
SD_Earn_results['cpctLWJobs']=SD_Earn_results['LWJobs_U30k_2050']/SD_Earn_results['totemp_2050']-SD_Earn_results['LWJobs_U30k_2015']/SD_Earn_results['totemp_2015']
SD_Earn_results['chhq1']=SD_Earn_results['hhincq1_2050']-SD_Earn_results['hhincq1_2015']
SD_Earn_results['cpcthhq1']=SD_Earn_results['hhincq1_2050']/SD_Earn_results['totemp_2050']-SD_Earn_results['hhincq1_2015']/SD_Earn_results['totemp_2015']
SD_Earn_results['cJHFit']=SD_Earn_results['Jobs-HH Fit_2050']-SD_Earn_results['Jobs-HH Fit_2015']
SD_Earn_results['JHFitcto1']=abs(SD_Earn_results['Jobs-HH Fit_2050']-1)<abs(SD_Earn_results['Jobs-HH Fit_2015']-1)

In [181]:
SD_Earn_results.rename({'SD_NAME_2015': 'SD_NAME', 'SD_ID_2015': 'SD_ID','County_2015': 'County'}, axis=1, inplace=True)
selected_columns = SD_Earn_results[["SD_ID","SD_NAME","County","Jobs-HH Fit_2015","Jobs-HH Fit_2050",'cJHFit','JHFitcto1','LWJobs_U30k_2015','cLWJobs','cpctLWJobs','hhincq1_2015','chhq1','cpcthhq1']]
SD_Earn_select = selected_columns.copy()

In [182]:
#71 out of 108 juris (including unincorporated) have JH Fit closer to 1
#21 out of 34 juris
SD_Earn_select['JHFitcto1'].sum()

21

In [205]:
SD_Earn_select

,SD_ID,SD_NAME,County,Jobs-HH Fit_2015,Jobs-HH Fit_2050,cJHFit,JHFitcto1,LWJobs_U30k_2015,cLWJobs,cpctLWJobs,hhincq1_2015,chhq1,cpcthhq1
0,1,Greater Downtown San Francisco,San Francisco,3.516182,4.525277,1.009095,False,145257.0,19540.0,-0.003075,41311,-4894,-0.018958
1,2,Richmond District,San Francisco,0.816456,1.055707,0.239251,True,26325.0,5039.0,0.009811,32243,-2534,-0.072689
2,3,Mission District,San Francisco,2.557606,3.515027,0.957421,False,83002.0,24013.0,-0.001276,32453,-2008,-0.029829
3,4,Sunset District,San Francisco,0.766063,1.147479,0.381416,True,9562.0,1930.0,0.005590,12482,-2467,-0.125287
4,5,Daly City/San Bruno,San Mateo,1.870981,2.101339,0.230357,False,35268.0,29718.0,0.018006,18850,12076,-0.008834
5,6,San Mateo/Burlingame,San Mateo,1.954947,1.575104,-0.379843,True,28769.0,3560.0,-0.003823,14716,5809,0.034920
6,7,Redwood City/Menlo Park,San Mateo,2.809042,2.329297,-0.479745,True,40012.0,12311.0,-0.003842,14244,8219,0.020003
7,8,Palo Alto/Los Altos,Santa Clara,2.572732,1.402975,-1.169757,True,43721.0,3722.0,0.009985,16994,16822,0.095181
8,9,Sunnyvale/Mountain View,Santa Clara,3.121111,2.606509,-0.514602,True,95403.0,126682.0,0.021325,30567,54637,0.024614
9,10,Cupertino/Saratoga,Santa Clara,1.486123,1.024742,-0.461380,True,41766.0,9963.0,0.003313,28104,22376,0.098076
10,11,Central San Jose,Santa Clara,1.438081,1.025797,-0.412284,True,52907.0,32863.0,-0.003075,36790,46823,0.086217
11,12,Milpitas/East San Jose,Santa Clara,1.323834,0.682022,-0.641813,True,33076.0,7462.0,0.021139,24985,34453,0.246187
12,13,South San Jose,Santa Clara,1.045220,0.860049,-0.185171,False,15810.0,8796.0,0.029175,15126,13484,0.097511
13,14,Gilroy/Morgan Hill,Santa Clara,1.931086,1.002836,-0.928249,True,15636.0,2750.0,0.001769,8097,10237,0.158569
14,15,Livermore/Pleasanton,Alameda,3.737470,1.977641,-1.759829,True,43549.0,11554.0,0.004950,11652,16211,0.086250
15,16,Fremont/Union City,Alameda,2.036157,1.785619,-0.250538,True,45502.0,32176.0,0.008759,22347,21155,0.027668
16,17,Hayward/San Leandro,Alameda,1.395180,2.137587,0.742407,False,50419.0,26175.0,0.005014,36138,-306,-0.082315
17,18,Oakland/Alameda,Alameda,1.258248,0.694212,-0.564035,False,92451.0,15456.0,-0.009148,73476,81962,0.213136
18,19,Berkeley/Albany,Alameda,1.791160,1.536651,-0.254509,True,47129.0,4189.0,-0.002532,26312,7084,0.029063
19,20,Richmond/El Cerrito,Contra Costa,1.060998,1.354738,0.293740,False,29361.0,16146.0,-0.003026,27673,5918,-0.081548
20,21,Concord/Martinez,Contra Costa,2.091181,2.270810,0.179629,False,43277.0,15948.0,0.000777,20695,5386,-0.014493
21,22,Walnut Creek,Contra Costa,2.380690,1.936107,-0.444583,True,27197.0,2772.0,0.019231,11424,4055,0.045311
22,23,Danville/San Ramon,Contra Costa,4.122969,1.995272,-2.127697,True,23604.0,1297.0,0.013998,5725,6755,0.107273
23,24,Antioch/Pittsburg,Contra Costa,0.959544,0.913316,-0.046228,False,21299.0,9003.0,0.016230,22197,10981,0.039156
24,25,Vallejo/Benicia,Solano,1.333097,1.438167,0.105070,False,18778.0,6016.0,0.011429,14086,3154,-0.016492
25,26,Fairfield/Vacaville,Solano,1.670555,1.185857,-0.484698,True,37524.0,15485.0,0.010641,22462,22239,0.120544
26,27,Napa,Napa,2.031342,2.391692,0.360351,False,18731.0,9137.0,0.017312,9221,2431,-0.024393
27,28,Saint Helena,Napa,2.340048,2.369152,0.029104,False,8712.0,2885.0,0.017985,3723,1172,0.005240
28,29,Petaluma/Rohnert Park,Sonoma,1.730854,1.572771,-0.158083,True,29042.0,6954.0,0.014020,16779,6108,0.034663
29,30,Santa Rosa/Sebastopol,Sonoma,1.849712,1.273483,-0.576229,True,47545.0,8827.0,0.016715,25704,18562,0.122184
30,31,Healdsburg/Cloverdale,Sonoma,1.198951,1.367683,0.168732,False,12348.0,6485.0,0.012656,10299,3471,-0.038007
31,32,Novato,Marin,2.107088,1.939379,-0.167709,True,9602.0,2203.0,0.012470,4557,1530,0.021630
32,33,San Rafael,Marin,2.312059,1.392308,-0.919751,True,21627.0,-5518.0,0.004499,9354,2216,0.114460
33,34,Mill Valley/Sausalito,Marin,2.547080,1.589338,-0.957742,True,14391.0,-737.0,0.012976,5650,2941,0.097359

In [206]:
selected_columnsTBL = SD_Earn_results[["SD_ID","SD_NAME","County",'cJHFit','JHFitcto1','LWJobs_U30k_2015','totemp_2015','hhincq1_2015','tothh_2015','LWJobs_U30k_2050','totemp_2050','hhincq1_2050','tothh_2050']]
SD_Earn_Tableau_30k = selected_columnsTBL.copy()

In [207]:
SD_Earn_Tableau_30k.to_csv('/Users/jeremyhalpern/Desktop/JHFit/Output/SD_JHFit_earnings.csv', index = False)

In [184]:
SD_Earn_results

,SD_ID,SD_NAME,County,Jobs-HH Fit_2015,LWJobs_U30k_2015,totemp_2015,hhincq1_2015,tothh_2015,U30k_AGREMPN_2015,U30k_FPSEMPN_2015,...,U30k_HEREMPN_2050,U30k_MWTEMPN_2050,U30k_OTHEMPN_2050,U30k_RETEMPN_2050,cLWJobs,cpctLWJobs,chhq1,cpcthhq1,cJHFit,JHFitcto1
0,1,Greater Downtown San Francisco,San Francisco,3.516182,145257.0,503985,41311,82670,0.551261,0.179497,...,0.390911,0.266310,0.197462,0.394243,19540.0,-0.003075,-4894,-0.018958,1.009095,False
1,2,Richmond District,San Francisco,0.816456,26325.0,89131,32243,107651,0.551261,0.179497,...,0.390911,0.266310,0.197462,0.394243,5039.0,0.009811,-2534,-0.072689,0.239251,True
2,3,Mission District,San Francisco,2.557606,83002.0,299990,32453,120451,0.551261,0.179497,...,0.390911,0.266310,0.197462,0.394243,24013.0,-0.001276,-2008,-0.029829,0.957421,False
3,4,Sunset District,San Francisco,0.766063,9562.0,31876,12482,51482,0.551261,0.179497,...,0.390911,0.266310,0.197462,0.394243,1930.0,0.005590,-2467,-0.125287,0.381416,True
4,5,Daly City/San Bruno,San Mateo,1.870981,35268.0,118738,18850,98467,0.677348,0.225675,...,0.458615,0.214988,0.207651,0.459893,29718.0,0.018006,12076,-0.008834,0.230357,False
5,6,San Mateo/Burlingame,San Mateo,1.954947,28769.0,95022,14716,88177,0.677348,0.225675,...,0.458615,0.214988,0.207651,0.459893,3560.0,-0.003823,5809,0.034920,-0.379843,True
6,7,Redwood City/Menlo Park,San Mateo,2.809042,40012.0,135488,14244,80473,0.677348,0.225675,...,0.458615,0.214988,0.207651,0.459893,12311.0,-0.003842,8219,0.020003,-0.479745,True
7,8,Palo Alto/Los Altos,Santa Clara,2.572732,43721.0,160895,16994,74044,0.578947,0.222321,...,0.450630,0.143861,0.200098,0.510513,3722.0,0.009985,16822,0.095181,-1.169757,True
8,9,Sunnyvale/Mountain View,Santa Clara,3.121111,95403.0,367252,30567,104278,0.578947,0.222321,...,0.450630,0.143861,0.200098,0.510513,126682.0,0.021325,54637,0.024614,-0.514602,True
9,10,Cupertino/Saratoga,Santa Clara,1.486123,41766.0,133415,28104,121282,0.578947,0.222321,...,0.450630,0.143861,0.200098,0.510513,9963.0,0.003313,22376,0.098076,-0.461380,True
10,11,Central San Jose,Santa Clara,1.438081,52907.0,165741,36790,103878,0.578947,0.222321,...,0.450630,0.143861,0.200098,0.510513,32863.0,-0.003075,46823,0.086217,-0.412284,True
11,12,Milpitas/East San Jose,Santa Clara,1.323834,33076.0,109260,24985,107570,0.578947,0.222321,...,0.450630,0.143861,0.200098,0.510513,7462.0,0.021139,34453,0.246187,-0.641813,True
12,13,South San Jose,Santa Clara,1.045220,15810.0,51215,15126,72909,0.578947,0.222321,...,0.450630,0.143861,0.200098,0.510513,8796.0,0.029175,13484,0.097511,-0.185171,False
13,14,Gilroy/Morgan Hill,Santa Clara,1.931086,15636.0,47797,8097,33886,0.578947,0.222321,...,0.450630,0.143861,0.200098,0.510513,2750.0,0.001769,10237,0.158569,-0.928249,True
14,15,Livermore/Pleasanton,Alameda,3.737470,43549.0,123809,11652,71852,0.518947,0.288963,...,0.440485,0.243724,0.248460,0.504846,11554.0,0.004950,16211,0.086250,-1.759829,True
15,16,Fremont/Union City,Alameda,2.036157,45502.0,137743,22347,105633,0.518947,0.288963,...,0.440485,0.243724,0.248460,0.504846,32176.0,0.008759,21155,0.027668,-0.250538,True
16,17,Hayward/San Leandro,Alameda,1.395180,50419.0,148251,36138,122047,0.518947,0.288963,...,0.440485,0.243724,0.248460,0.504846,26175.0,0.005014,-306,-0.082315,0.742407,False
17,18,Oakland/Alameda,Alameda,1.258248,92451.0,263784,73476,179808,0.518947,0.288963,...,0.440485,0.243724,0.248460,0.504846,15456.0,-0.009148,81962,0.213136,-0.564035,False
18,19,Berkeley/Albany,Alameda,1.791160,47129.0,141903,26312,73559,0.518947,0.288963,...,0.440485,0.243724,0.248460,0.504846,4189.0,-0.002532,7084,0.029063,-0.254509,True
19,20,Richmond/El Cerrito,Contra Costa,1.060998,29361.0,75651,27673,89524,0.461035,0.305870,...,0.492633,0.235548,0.276007,0.598640,16146.0,-0.003026,5918,-0.081548,0.293740,False
20,21,Concord/Martinez,Contra Costa,2.091181,43277.0,110346,20695,85687,0.461035,0.305870,...,0.492633,0.235548,0.276007,0.598640,15948.0,0.000777,5386,-0.014493,0.179629,False
21,22,Walnut Creek,Contra Costa,2.380690,27197.0,74150,11424,60323,0.461035,0.305870,...,0.492633,0.235548,0.276007,0.598640,2772.0,0.019231,4055,0.045311,-0.444583,True
22,23,Danville/San Ramon,Contra Costa,4.122969,23604.0,60893,5725,54100,0.461035,0.305870,...,0.492633,0.235548,0.276007,0.598640,1297.0,0.013998,6755,0.107273,-2.127697,True
23,24,Antioch/Pittsburg,Contra Costa,0.959544,21299.0,52537,22197,92948,0.461035,0.305870,...,0.492633,0.235548,0.276007,0.598640,9003.0,0.016230,10981,0.039156,-0.046228,False
24,25,Vallejo/Benicia,Solano,1.333097,18778.0,42108,14086,53073,0.651843,0.468907,...,0.505246,0.299264,0.238870,0.687209,6016.0,0.011429,3154,-0.016492,0.105070,False
25,26,Fairfield/Vacaville,Solano,1.670555,37524.0,82288,22462,90647,0.651843,0.468907,...,0.505246,0.299264,0.238870,0.687209,15485.0,0.010641,22239,0.120544,-0.484698,True
26,27,Napa,Napa,2.031342,18731.0,43922,9221,34658,0.565883,0.415765,...,0.487895,0.271080,0.329726,0.584123,9137.0,0.017312,2431,-0.024393,0.360351,False
27,28,Saint Helena,Napa,2.340048,8712.0,19448,3723,16367,0.565883,0.415765,...,0.487895,0.271080,0.329726,0.584123,2885.0,0.017985,1172,0.005240,0.029104,False
28,29,Petaluma/Rohnert Park,Sonoma,1.730854,29042.0,65498,16779,65047,0.575175,0.429085,...,0.525208,0.299098,0.323985,0.600765,6954.0,0.014020,6108,0.034663,-0.158083,True
29,30,Santa Rosa/Sebastopol,Sonoma,1.849712,47545.0,106645,25704,88836,0.575175,0.429085,...,0.525208,0.299098,0.323985,0.600765,8827.0,0.016715,18562,0.122184,-0.576229,True
30,31,Healdsburg/Cloverdale,Sonoma,1.198951,12348.0,26885,10299,36317,0.575175,0.429085,...,0.525208,0.299098,0.323985,0.600765,6485.0,0.012656,3471,-0.038007,0.168732,False
31,32,Novato,Marin,2.107088,9602.0,25926,4557,23202,0.631417,0.391711,...,0.491337,0.261903,0.259190,0.495497,2203.0,0.012470,1530,0.021630,-0.167709,True
32,33,San Rafael,Marin,2.312059,21627.0,55554,9354,44231,0.631417,0.391711,...,0.491337,0.261903,0.259190,0.495497,-5518.0,0.004499,2216,0.114460,-0.919751,True
33,34,Mill Valley/Sausalito,Marin,2.547080,14391.0,38172,5650,41499,0.631417,0.391711,...,0.491337,0.261903,0.259190,0.495497,-737.0,0.012976,2941,0.097359,-0.957742,True

In [153]:
county15_Eshares=juris15_Eshares.groupby("County").sum()
county50_Eshares=juris50_Eshares.groupby("County").sum()

In [442]:
county15_Eshares['Jobs-HH Fit']=county15_Eshares['LWJobs_U40k']/county15_Eshares['hhincq1']
county50_Eshares['Jobs-HH Fit']=county50_Eshares['LWJobs_U40k']/county50_Eshares['hhincq1']

In [443]:
#Note County is index
selected_columns = county15_Eshares[["Jobs-HH Fit",'LWJobs_U40k','totemp','hhincq1','tothh']]
County15_Earn_export = selected_columns.copy()
selected_columns2 = county50_Eshares[["Jobs-HH Fit",'LWJobs_U40k','totemp','hhincq1','tothh']]
County50_Earn_export = selected_columns2.copy()

In [444]:
County15_Earn_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\County2015_JHFit_Earnings.csv')
County50_Earn_export.to_csv(r'C:\Users\jhalpern\Box\Horizon and Plan Bay Area 2050\Equity and Performance\7_Analysis\Jobs-Housing Fit\Outputs\County2050_JHFit_Earnings.csv')